In [2]:
import pandas as pd

In [5]:
# Path to the downloaded Excel file
excel_file_path = "../data/landing/Data_Tables_Property_Items_Visualisation_Year_Ending_March_2023.xlsx"

# Read the Excel file into a Pandas DataFrame
xls = pd.ExcelFile(excel_file_path)

In [9]:
# List the sheet names in the Excel file
sheet_names = xls.sheet_names

# Print the sheet names
print("Sheet names:", sheet_names)

#Table 01 has lots of granularity, with number of items, value, postcode, property item by year
#Table 02 has offence count and offence type by LGA
#Table 04 has offence count by LGA 
#Table 06 has postcode offence count year


# Example: Read a specific sheet into a DataFrame
sheet_name_to_read = "Table 06"  
df = pd.read_excel(excel_file_path, sheet_name=sheet_name_to_read)

df.head(5)

Sheet names: ['Contents', 'Footnotes', 'Table 01', 'Table 02', 'Table 03', 'Table 04', 'Table 05', 'Table 06']

,Year,Year ending,Police Region,Local Government Area,Postcode,Suburb/Town,Offence Count
0,2023,March,1 North West Metro,Banyule,3079,Ivanhoe,27
1,2023,March,1 North West Metro,Banyule,3079,Ivanhoe East,3
2,2023,March,1 North West Metro,Banyule,3081,Bellfield,5
3,2023,March,1 North West Metro,Banyule,3081,Heidelberg Heights,15
4,2023,March,1 North West Metro,Banyule,3081,Heidelberg West,26

In [64]:
# Attempt to convert the 'postcode' column to integers, and use errors='coerce' to set non-convertible values to NaN
df['Postcode'] = pd.to_numeric(df['Postcode'], errors='coerce')

# Drop rows where 'postcode' is NaN (i.e., not a valid integer)
df = df.dropna(subset=['Postcode'])

df_sorted = df.sort_values(by=['Suburb/Town', 'Year'], ascending=True)

df_sorted.head(5)

,Year,Year ending,Police Region,Local Government Area,Postcode,Suburb/Town,Offence Count
8198,2014,March,1 North West Metro,Yarra,3067.0,Abbotsford,24
7432,2015,March,1 North West Metro,Yarra,3067.0,Abbotsford,24
6600,2016,March,1 North West Metro,Yarra,3067.0,Abbotsford,19
5718,2017,March,1 North West Metro,Yarra,3067.0,Abbotsford,38
4851,2018,March,1 North West Metro,Yarra,3067.0,Abbotsford,34

In [19]:
# Group the DataFrame by 'suburb_town' and count the unique 'postcode' values in each group
postcode_counts = df.groupby('Suburb/Town')['Postcode'].nunique().reset_index()

# Rename the columns for clarity (optional)
postcode_counts.columns = ['Suburb/Town', 'unique_postcode_count']

            Suburb  unique_postcode_count
0       Abbotsford                      1
1       Aberfeldie                      1
2          Aintree                      1
3     Aireys Inlet                      1
4     Airport West                      1
...            ...                    ...
1560        Yinnar                      1
1561      Yulecart                      1
1562        Yuroke                      1
1563       Yuulong                      1
1564       Zeerust                      1

[1565 rows x 2 columns]

In [46]:
postcode_counts.sort_values(by=['unique_postcode_count'], ascending=True)

filtered_df = postcode_counts[postcode_counts['unique_postcode_count'] != 1]
filtered_df.head(30)

              Suburb  unique_postcode_count
37             Ascot                      2
101        Beaumaris                      2
181    Brighton East                      2
189   Brunswick East                      2
199          Bulleen                      2
257          Carlton                      2
299     Clifton Hill                      3
408        Doncaster                      2
491    Fitzroy North                      2
622          Highett                      2
841          Malvern                      2
871        Melbourne                      4
887         Merrijig                      2
1025         Newtown                      2
1344         Thomson                      2
1433  Wantirna South                      2
1504         Windsor                      2

In [60]:
grouped_counts = df.groupby(['Suburb/Town', 'Postcode']).size().reset_index(name='counts')
grouped_counts.head(50)
grouped_counts[grouped_counts['Suburb/Town'] == 'Boronia']
# Ascot, Merijig, Newtown, Thomson has 2 unique locations
# Boronia and Wantirna South have some Muddles
# Melbourne has a few

    Suburb/Town  Postcode  counts
164     Boronia    3155.0      10

In [74]:
#now go through the raw data and change any that have the incorrect values

dont_change = ['Ascot', 'Merijig', 'Newtown', 'Thomson', 'Wantirna South', 'Melbourne']

          Suburb/Town  Postcode  counts
0          Abbotsford    3067.0       1
1          Aberfeldie    3040.0       1
2             Aintree    3336.0       1
3        Airport West    3042.0       1
4           Albanvale    3021.0       1
5         Albert Park    3206.0       1
6              Albion    3020.0       1
7           Alexandra    3714.0       1
8           Alfredton    3350.0       1
9                Alma    3465.0       1
11             Altona    3018.0       1
12     Altona Meadows    3028.0       1
13       Altona North    3025.0       1
14             Anakie    3213.0       1
15             Ancona    3715.0       1
16           Anglesea    3230.0       1
17             Ararat    3377.0       1
18             Ardeer    3022.0       1
19           Armadale    3143.0       1
20    Armstrong Creek    3217.0       1
21      Arthurs Creek    3099.0       1
22              Ascot    3551.0       1
23         Ascot Vale    3032.0       1
24          Ashburton    3147.0       1
25            Ashwood    3147.0       1
26          Aspendale    3195.0       1
27  Aspendale Gardens    3195.0       1
28            Attwood    3049.0       1
29             Avalon    3212.0       1
31   Avondale Heights    3034.0       1