In [100]:
import pandas as pd
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.preprocessing import StandardScaler

In [101]:
data = pd.read_csv("../data/curated/merged_data.csv")
print(list(data.columns))

['property type', 'beds', 'baths', 'parking', 'weekly rent amount', 'postcode', 'distance primary school', 'distance secondary school', 'is closest school good', 'closest university campus', 'distance university campus', 'closest hospital', 'distance to closest hospital', 'offence count 2023', 'estimated resident population (no.) 2011', 'total dwellings (no.) 2017', 'median equivalised total household income (weekly) ($) 2011', 'median weekly household rental payment ($) 2011', 'average family size (no. of persons) 2011', 'estimated resident population (no.) 2016', 'total dwellings (no.) 2019', 'median equivalised total household income (weekly) ($) 2016', 'median weekly household rental payment ($) 2016', 'average family size (no. of persons) 2016', 'estimated resident population (no.) 2021', 'total dwellings (no.) 2021', 'median equivalised total household income (weekly) ($) 2021', 'median weekly household rental payment ($) 2021', 'average family size (no. of persons) 2021', 'total_supermarkets', 'major_supermarkets', 'city_centre', 'closest_city_centre', 'coastal', 'closest_cc_dist', 'dist_to_melb', 'employment ratio 2011', 'employment ratio 2016', 'employment ratio 2021']

In [102]:
data = data.drop(["closest university campus", "closest hospital"], axis=1)

In [103]:
def predict_2023_value(y_values, col_name, x_values = [0,5,10]): 
    """ 
    Function predicts 2023 value of variable given past data. Assumes linear relationship.
    default value of x_value 0, 5, 10 represents 2011, 2016, 2021
    """
    # 0, 5, 10 represents 2011, 2016, 2021
    print(y_values)
    print(col_name)
    model = LinearRegression()
    x_values = np.array(x_values).reshape(-1,1)
    y_values = np.array(y_values).reshape(-1,1)
    model.fit(x_values, y_values)
    # 12 represents 2023
    predict_2023 = model.predict(np.array(12).reshape(-1,1))
    return pd.Series({col_name: predict_2023[0][0]})

In [104]:

# predict median equivalised total household income (weekly) ($) 2023
median_income_2023_column = data.apply(lambda x:
    predict_2023_value([x["median equivalised total household income (weekly) ($) 2011"], 
     x["median equivalised total household income (weekly) ($) 2016"],
     x["median equivalised total household income (weekly) ($) 2021"]], 
    "predicted median equivalised total household income (weekly) ($) 2023"), axis=1)

data = pd.concat([data, median_income_2023_column], axis=1)
data[["median equivalised total household income (weekly) ($) 2011", 
     "median equivalised total household income (weekly) ($) 2016",
     "median equivalised total household income (weekly) ($) 2021", 
     "predicted median equivalised total household income (weekly) ($) 2023"]]

data = data.drop(["median equivalised total household income (weekly) ($) 2011", 
     "median equivalised total household income (weekly) ($) 2016",
     "median equivalised total household income (weekly) ($) 2021"], axis=1)

[1089.0, 1265.6666666666667, 1495.0]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[628.0, 761.0, 931.0]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[509.0, 560.0, 637.0]
predicted median equivalised total household income (weekly) ($) 2023
[575.25, 651.25, 812.75]
predicted median equivalised total household income (weekly) ($) 2023
[697.6, 758.2, 988.8]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[1201.0, 1361.0, 1578.5]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[658.0, 745.0, 909.0]
predicted median equivalised total household income (weekly) ($) 2023
[542.0, 624.0, 774.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[542.0, 624.0, 774.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[574.75, 624.5, 737.75]
predicted median equivalised total household income (weekly) ($) 2023
[591.6666666666666, 655.0, 942.3333333333334]
predicted median equivalised total household income (weekly) ($) 2023
[616.25, 734.0, 976.25]
predicted median equivalised total household income (weekly) ($) 2023
[579.0, 646.0, 819.0]
predicted median equivalised total household income (weekly) ($) 2023
[766.0, 878.0, 1065.0]
predicted median equivalised total household income (weekly) ($) 2023
[560.0, 670.0, 795.0]
predicted median equivalised total household income (weekly) ($) 2023
[697.6, 758.2, 988.8]
predicted median equivalised total household income (weekly) ($) 2023
[697.6, 758.2, 988.8]
predicted median equivalised total household income (weekly) ($) 2023
[616.25, 734.0, 976.25]
predicted median equivalised total household income (weekly) ($) 2023
[591.6666666666666, 655.0, 942.3333333333334]
predicted median equivalised total household income (weekly) ($) 2023
[542.0, 624.0, 774.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[674.6666666666666, 829.0, 1104.0]
predicted median equivalised total household income (weekly) ($) 2023
[710.25, 895.5, 1230.75]
predicted median equivalised total household income (weekly) ($) 2023
[798.5, 894.5, 1124.5]
predicted median equivalised total household income (weekly) ($) 2023
[588.0, 661.0, 794.0]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[710.25, 895.5, 1230.75]
predicted median equivalised total household income (weekly) ($) 2023
[697.6, 758.2, 988.8]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[756.5, 871.5, 1086.5]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[766.0, 878.0, 1065.0]
predicted median equivalised total household income (weekly) ($) 2023
[542.0, 624.0, 774.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[588.5, 674.0, 846.5]
predicted median equivalised total household income (weekly) ($) 2023
[742.5, 839.0, 998.5]
predicted median equivalised total household income (weekly) ($) 2023
[738.5, 828.5, 975.5]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[718.0, 807.0, 1062.0]
predicted median equivalised total household income (weekly) ($) 2023
[545.0, 635.0, 726.0]
predicted median equivalised total household income (weekly) ($) 2023
[1299.3333333333333, 1442.0, 1709.6666666666667]
predicted median equivalised total household income (weekly) ($) 2023
[718.0, 807.0, 1062.0]
predicted median equivalised total household income (weekly) ($) 2023
[579.0, 646.0, 819.0]
predicted median equivalised total household income (weekly) ($) 2023
[830.0, 1021.0, 1395.0]
predicted median equivalised total household income (weekly) ($) 2023
[852.0, 1006.0, 1315.0]
predicted median equivalised total household income (weekly) ($) 2023
[556.0, 659.0, 834.0]
predicted median equivalised total household income (weekly) ($) 2023
[697.6, 758.2, 988.8]
predicted median equivalised total household income (weekly) ($) 2023
[697.6, 758.2, 988.8]
predicted median equivalised total household income (weekly) ($) 2023
[560.0, 670.0, 795.0]
predicted median equivalised total household income (weekly) ($) 2023
[629.0, 689.0, 845.0]
predicted median equivalised total household income (weekly) ($) 2023
[575.25, 651.25, 812.75]
predicted median equivalised total household income (weekly) ($) 2023
[542.0, 624.0, 774.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[575.25, 651.25, 812.75]
predicted median equivalised total household income (weekly) ($) 2023
[516.0, 610.0, 681.0]
predicted median equivalised total household income (weekly) ($) 2023
[718.0, 807.0, 1062.0]
predicted median equivalised total household income (weekly) ($) 2023
[510.0, 571.0, 735.0]
predicted median equivalised total household income (weekly) ($) 2023
[510.0, 571.0, 735.0]
predicted median equivalised total household income (weekly) ($) 2023
[542.0, 624.0, 774.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[509.0, 560.0, 637.0]
predicted median equivalised total household income (weekly) ($) 2023
[689.3333333333334, 797.0, 990.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[658.0, 745.0, 909.0]
predicted median equivalised total household income (weekly) ($) 2023
[591.6666666666666, 655.0, 942.3333333333334]
predicted median equivalised total household income (weekly) ($) 2023
[650.0, 726.6666666666666, 868.0]
predicted median equivalised total household income (weekly) ($) 2023
[509.0, 560.0, 637.0]
predicted median equivalised total household income (weekly) ($) 2023
[679.25, 779.5, 954.875]
predicted median equivalised total household income (weekly) ($) 2023
[811.5, 972.0, 1216.0]
predicted median equivalised total household income (weekly) ($) 2023
[708.0, 811.0, 1090.0]
predicted median equivalised total household income (weekly) ($) 2023
[665.5, 761.5, 937.0]
predicted median equivalised total household income (weekly) ($) 2023
[718.0, 807.0, 1062.0]
predicted median equivalised total household income (weekly) ($) 2023
[673.25, 768.5, 954.0]
predicted median equivalised total household income (weekly) ($) 2023
[852.0, 980.5, 1216.0]
predicted median equivalised total household income (weekly) ($) 2023
[616.5, 703.5, 856.5]
predicted median equivalised total household income (weekly) ($) 2023
[565.0, 634.0, 779.0]
predicted median equivalised total household income (weekly) ($) 2023
[830.0, 1021.0, 1395.0]
predicted median equivalised total household income (weekly) ($) 2023
[591.6666666666666, 655.0, 942.3333333333334]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[718.0, 807.0, 1062.0]
predicted median equivalised total household income (weekly) ($) 2023
[718.0, 807.0, 1062.0]
predicted median equivalised total household income (weekly) ($) 2023
[591.6666666666666, 655.0, 942.3333333333334]
predicted median equivalised total household income (weekly) ($) 2023
[738.5, 828.5, 975.5]
predicted median equivalised total household income (weekly) ($) 2023
[738.6666666666666, 847.3333333333334, 996.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[629.0, 689.0, 845.0]
predicted median equivalised total household income (weekly) ($) 2023
[697.0, 813.0, 1045.6666666666667]
predicted median equivalised total household income (weekly) ($) 2023
[650.0, 726.6666666666666, 868.0]
predicted median equivalised total household income (weekly) ($) 2023
[588.0, 643.0, 790.0]
predicted median equivalised total household income (weekly) ($) 2023
[775.0, 852.5, 1056.5]
predicted median equivalised total household income (weekly) ($) 2023
[772.5, 857.5, 1033.5]
predicted median equivalised total household income (weekly) ($) 2023
[593.0, 681.0, 815.0]
predicted median equivalised total household income (weekly) ($) 2023
[797.5, 951.5, 1236.0]
predicted median equivalised total household income (weekly) ($) 2023
[657.0, 751.0, 954.0]
predicted median equivalised total household income (weekly) ($) 2023
[1201.0, 1361.0, 1578.5]
predicted median equivalised total household income (weekly) ($) 2023
[565.0, 634.0, 779.0]
predicted median equivalised total household income (weekly) ($) 2023
[775.0, 852.5, 1056.5]
predicted median equivalised total household income (weekly) ($) 2023
[775.0, 852.5, 1056.5]
predicted median equivalised total household income (weekly) ($) 2023
[775.0, 852.5, 1056.5]
predicted median equivalised total household income (weekly) ($) 2023
[542.0, 624.0, 774.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[797.4, 849.2, 1072.7]
predicted median equivalised total household income (weekly) ($) 2023
[738.6666666666666, 847.3333333333334, 996.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[679.25, 779.5, 954.875]
predicted median equivalised total household income (weekly) ($) 2023
[566.0, 647.0, 790.0]
predicted median equivalised total household income (weekly) ($) 2023
[563.75, 657.0, 866.0]
predicted median equivalised total household income (weekly) ($) 2023
[811.5, 972.0, 1216.0]
predicted median equivalised total household income (weekly) ($) 2023
[797.4, 849.2, 1072.7]
predicted median equivalised total household income (weekly) ($) 2023
[738.5, 828.5, 975.5]
predicted median equivalised total household income (weekly) ($) 2023
[1201.0, 1361.0, 1578.5]
predicted median equivalised total household income (weekly) ($) 2023
[643.3333333333334, 782.5, 1049.1666666666667]
predicted median equivalised total household income (weekly) ($) 2023
[573.5, 669.5, 850.5]
predicted median equivalised total household income (weekly) ($) 2023
[591.6666666666666, 655.0, 942.3333333333334]
predicted median equivalised total household income (weekly) ($) 2023
[534.0, 608.0, 752.0]
predicted median equivalised total household income (weekly) ($) 2023
[591.0, 691.0, 840.0]
predicted median equivalised total household income (weekly) ($) 2023
[667.0, 723.0, 907.0]
predicted median equivalised total household income (weekly) ($) 2023
[591.6666666666666, 655.0, 942.3333333333334]
predicted median equivalised total household income (weekly) ($) 2023
[1058.0, 1231.0, 1487.0]
predicted median equivalised total household income (weekly) ($) 2023
[932.5714285714286, 968.2857142857144, 1175.428571428571]
predicted median equivalised total household income (weekly) ($) 2023
[1051.0, 1216.5, 1521.5]
predicted median equivalised total household income (weekly) ($) 2023
[718.0, 807.0, 1062.0]
predicted median equivalised total household income (weekly) ($) 2023
[650.0, 726.6666666666666, 868.0]
predicted median equivalised total household income (weekly) ($) 2023
[511.0, 576.0, 675.0]
predicted median equivalised total household income (weekly) ($) 2023
[775.0, 852.5, 1056.5]
predicted median equivalised total household income (weekly) ($) 2023
[573.5, 669.5, 850.5]
predicted median equivalised total household income (weekly) ($) 2023
[665.5, 756.5, 935.0]
predicted median equivalised total household income (weekly) ($) 2023
[689.3333333333334, 797.0, 990.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[697.6, 758.2, 988.8]
predicted median equivalised total household income (weekly) ($) 2023
[545.0, 635.0, 726.0]
predicted median equivalised total household income (weekly) ($) 2023
[545.0, 635.0, 726.0]
predicted median equivalised total household income (weekly) ($) 2023
[738.5, 828.5, 975.5]
predicted median equivalised total household income (weekly) ($) 2023
[650.0, 726.6666666666666, 868.0]
predicted median equivalised total household income (weekly) ($) 2023
[609.0, 697.0, 833.0]
predicted median equivalised total household income (weekly) ($) 2023
[830.0, 1021.0, 1395.0]
predicted median equivalised total household income (weekly) ($) 2023
[1051.0, 1216.5, 1521.5]
predicted median equivalised total household income (weekly) ($) 2023
[679.25, 779.5, 954.875]
predicted median equivalised total household income (weekly) ($) 2023
[679.25, 779.5, 954.875]
predicted median equivalised total household income (weekly) ($) 2023
[591.6666666666666, 655.0, 942.3333333333334]
predicted median equivalised total household income (weekly) ($) 2023
[639.0, 719.0, 898.0]
predicted median equivalised total household income (weekly) ($) 2023
[639.0, 719.0, 898.0]
predicted median equivalised total household income (weekly) ($) 2023
[571.0, 631.0, 772.0]
predicted median equivalised total household income (weekly) ($) 2023
[738.6666666666666, 847.3333333333334, 996.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[718.0, 807.0, 1062.0]
predicted median equivalised total household income (weekly) ($) 2023
[1299.3333333333333, 1442.0, 1709.6666666666667]
predicted median equivalised total household income (weekly) ($) 2023
[738.5, 828.5, 975.5]
predicted median equivalised total household income (weekly) ($) 2023
[680.0, 763.0, 919.0]
predicted median equivalised total household income (weekly) ($) 2023
[509.0, 560.0, 637.0]
predicted median equivalised total household income (weekly) ($) 2023
[554.0, 632.0, 726.0]
predicted median equivalised total household income (weekly) ($) 2023
[901.2, 1035.6, 1273.6]
predicted median equivalised total household income (weekly) ($) 2023
[738.5, 828.5, 975.5]
predicted median equivalised total household income (weekly) ($) 2023
[543.0, 666.0, 834.0]
predicted median equivalised total household income (weekly) ($) 2023
[509.0, 560.0, 637.0]
predicted median equivalised total household income (weekly) ($) 2023
[663.5, 768.5, 940.0]
predicted median equivalised total household income (weekly) ($) 2023
[863.3333333333334, 979.3333333333334, 1344.6666666666667]
predicted median equivalised total household income (weekly) ($) 2023
[775.0, 852.5, 1056.5]
predicted median equivalised total household income (weekly) ($) 2023
[1051.0, 1216.5, 1521.5]
predicted median equivalised total household income (weekly) ($) 2023
[509.0, 560.0, 637.0]
predicted median equivalised total household income (weekly) ($) 2023
[852.0, 1006.0, 1315.0]
predicted median equivalised total household income (weekly) ($) 2023
[573.5, 669.5, 850.5]
predicted median equivalised total household income (weekly) ($) 2023
[775.0, 852.5, 1056.5]
predicted median equivalised total household income (weekly) ($) 2023
[509.0, 560.0, 637.0]
predicted median equivalised total household income (weekly) ($) 2023
[663.5, 768.5, 940.0]
predicted median equivalised total household income (weekly) ($) 2023
[509.0, 560.0, 637.0]
predicted median equivalised total household income (weekly) ($) 2023
[663.5, 768.5, 940.0]
predicted median equivalised total household income (weekly) ($) 2023
[775.0, 959.0, 1210.0]
predicted median equivalised total household income (weekly) ($) 2023
[516.0, 610.0, 681.0]
predicted median equivalised total household income (weekly) ($) 2023
[665.5, 761.5, 937.0]
predicted median equivalised total household income (weekly) ($) 2023
[616.5, 703.5, 856.5]
predicted median equivalised total household income (weekly) ($) 2023
[624.0, 721.0, 881.0]
predicted median equivalised total household income (weekly) ($) 2023
[593.0, 681.0, 815.0]
predicted median equivalised total household income (weekly) ($) 2023
[477.0, 517.5, 618.0]
predicted median equivalised total household income (weekly) ($) 2023
[572.3333333333334, 647.6666666666666, 783.3333333333334]
predicted median equivalised total household income (weekly) ($) 2023
[749.6666666666666, 908.0, 1161.0]
predicted median equivalised total household income (weekly) ($) 2023
[966.0, 1164.0, 1510.0]
predicted median equivalised total household income (weekly) ($) 2023
[775.0, 852.5, 1056.5]
predicted median equivalised total household income (weekly) ($) 2023
[863.3333333333334, 979.3333333333334, 1344.6666666666667]
predicted median equivalised total household income (weekly) ($) 2023
[738.5, 828.5, 975.5]
predicted median equivalised total household income (weekly) ($) 2023
[542.0, 624.0, 774.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[1051.0, 1216.5, 1521.5]
predicted median equivalised total household income (weekly) ($) 2023
[572.3333333333334, 647.6666666666666, 783.3333333333334]
predicted median equivalised total household income (weekly) ($) 2023
[1244.3333333333333, 1357.6666666666667, 1612.0]
predicted median equivalised total household income (weekly) ($) 2023
[616.5, 703.5, 856.5]
predicted median equivalised total household income (weekly) ($) 2023
[621.0, 737.0, 882.0]
predicted median equivalised total household income (weekly) ($) 2023
[650.0, 726.6666666666666, 868.0]
predicted median equivalised total household income (weekly) ($) 2023
[591.0, 691.0, 840.0]
predicted median equivalised total household income (weekly) ($) 2023
[522.0, 588.0, 782.0]
predicted median equivalised total household income (weekly) ($) 2023
[710.25, 895.5, 1230.75]
predicted median equivalised total household income (weekly) ($) 2023
[689.3333333333334, 797.0, 990.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[591.0, 691.0, 840.0]
predicted median equivalised total household income (weekly) ($) 2023
[741.5, 831.5, 1026.5]
predicted median equivalised total household income (weekly) ($) 2023
[573.5, 669.5, 850.5]
predicted median equivalised total household income (weekly) ($) 2023
[550.0, 660.0, 829.0]
predicted median equivalised total household income (weekly) ($) 2023
[510.0, 571.0, 735.0]
predicted median equivalised total household income (weekly) ($) 2023
[509.0, 560.0, 637.0]
predicted median equivalised total household income (weekly) ($) 2023
[573.5, 669.5, 850.5]
predicted median equivalised total household income (weekly) ($) 2023
[543.0, 666.0, 834.0]
predicted median equivalised total household income (weekly) ($) 2023
[653.0, 758.0, 887.0]
predicted median equivalised total household income (weekly) ($) 2023
[555.0, 619.0, 729.0]
predicted median equivalised total household income (weekly) ($) 2023
[674.6666666666666, 829.0, 1104.0]
predicted median equivalised total household income (weekly) ($) 2023
[591.6666666666666, 655.0, 942.3333333333334]
predicted median equivalised total household income (weekly) ($) 2023
[915.0, 1258.0, 1693.0]
predicted median equivalised total household income (weekly) ($) 2023
[1086.0, 1222.3333333333333, 1488.0]
predicted median equivalised total household income (weekly) ($) 2023
[800.5, 876.5, 1295.0]
predicted median equivalised total household income (weekly) ($) 2023
[650.0, 726.6666666666666, 868.0]

In [105]:
# median weekly household rental payment ($) 2023
weekly_rent_2023_column = data.apply(lambda x:
    predict_2023_value([x["median weekly household rental payment ($) 2011"], 
     x["median weekly household rental payment ($) 2016"],
     x["median weekly household rental payment ($) 2021"]], 
    "predicted median weekly household rental payment ($) 2023"), axis=1)

data = pd.concat([data, weekly_rent_2023_column], axis=1)

data[["median weekly household rental payment ($) 2011", 
     "median weekly household rental payment ($) 2016",
     "median weekly household rental payment ($) 2021", 
     "predicted median weekly household rental payment ($) 2023"]]


data = data.drop(["median weekly household rental payment ($) 2011", 
     "median weekly household rental payment ($) 2016",
     "median weekly household rental payment ($) 2021"], axis=1)

[367.0, 420.3333333333333, 466.0]
predicted median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
predicted median weekly household rental payment ($) 2023
[271.0, 330.0, 405.0]
predicted median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
predicted median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
predicted median weekly household rental payment ($) 2023
[150.0, 180.0, 215.0]
predicted median weekly household rental payment ($) 2023
[255.5, 300.5, 334.5]
predicted median weekly household rental payment ($) 2023
[309.6, 334.4, 372.8]
predicted median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
predicted median weekly household rental payment ($) 2023
[360.0, 391.0, 406.5]
predicted median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
predicted median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
predicted median weekly household rental payment ($) 2023
[240.0, 280.0, 330.0]
predicted median weekly household rental payment ($) 2023
[250.0, 293.3333333333333, 330.6666666666667]
predicted median weekly household rental payment ($) 2023
[250.0, 293.3333333333333, 330.6666666666667]
predicted median weekly household rental payment ($) 2023
[257.5, 296.5, 334.0]
predicted median weekly household rental payment ($) 2023
[311.0, 356.0, 387.3333333333333]
predicted median weekly household rental payment ($) 2023
[276.75, 316.0, 359.75]
predicted median weekly household rental payment ($) 2023
[200.0, 250.0, 285.0]
predicted median weekly household rental payment ($) 2023
[323.0, 381.0, 430.0]
predicted median weekly household rental payment ($) 2023
[160.0, 180.0, 210.0]
predicted median weekly household rental payment ($) 2023
[309.6, 334.4, 372.8]
predicted median weekly household rental payment ($) 2023
[309.6, 334.4, 372.8]
predicted median weekly household rental payment ($) 2023
[276.75, 316.0, 359.75]
predicted median weekly household rental payment ($) 2023
[311.0, 356.0, 387.3333333333333]
predicted median weekly household rental payment ($) 2023
[250.0, 293.3333333333333, 330.6666666666667]
predicted median weekly household rental payment ($) 2023
[287.0, 334.0, 380.0]
predicted median weekly household rental payment ($) 2023
[267.0, 324.5, 378.75]
predicted median weekly household rental payment ($) 2023
[306.5, 345.5, 384.5]
predicted median weekly household rental payment ($) 2023
[150.0, 180.0, 214.0]
predicted median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
predicted median weekly household rental payment ($) 2023
[267.0, 324.5, 378.75]
predicted median weekly household rental payment ($) 2023
[309.6, 334.4, 372.8]
predicted median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
predicted median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
predicted median weekly household rental payment ($) 2023
[305.5, 356.0, 393.5]
predicted median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
predicted median weekly household rental payment ($) 2023
[323.0, 381.0, 430.0]
predicted median weekly household rental payment ($) 2023
[250.0, 293.3333333333333, 330.6666666666667]
predicted median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
predicted median weekly household rental payment ($) 2023
[192.5, 250.0, 310.0]
predicted median weekly household rental payment ($) 2023
[305.0, 331.0, 367.0]
predicted median weekly household rental payment ($) 2023
[207.5, 240.0, 275.0]
predicted median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
predicted median weekly household rental payment ($) 2023
[335.3333333333333, 389.6666666666667, 418.3333333333333]
predicted median weekly household rental payment ($) 2023
[175.0, 208.0, 250.0]
predicted median weekly household rental payment ($) 2023
[375.3333333333333, 414.6666666666667, 426.0]
predicted median weekly household rental payment ($) 2023
[335.3333333333333, 389.6666666666667, 418.3333333333333]
predicted median weekly household rental payment ($) 2023
[200.0, 250.0, 285.0]
predicted median weekly household rental payment ($) 2023
[277.5, 328.0, 384.5]
predicted median weekly household rental payment ($) 2023
[340.0, 405.0, 500.0]
predicted median weekly household rental payment ($) 2023
[160.0, 195.0, 220.0]
predicted median weekly household rental payment ($) 2023
[309.6, 334.4, 372.8]
predicted median weekly household rental payment ($) 2023
[309.6, 334.4, 372.8]
predicted median weekly household rental payment ($) 2023
[160.0, 180.0, 210.0]
predicted median weekly household rental payment ($) 2023
[170.0, 200.0, 235.0]
predicted median weekly household rental payment ($) 2023
[255.5, 300.5, 334.5]
predicted median weekly household rental payment ($) 2023
[250.0, 293.3333333333333, 330.6666666666667]
predicted median weekly household rental payment ($) 2023
[255.5, 300.5, 334.5]
predicted median weekly household rental payment ($) 2023
[143.0, 170.0, 200.0]
predicted median weekly household rental payment ($) 2023
[335.3333333333333, 389.6666666666667, 418.3333333333333]
predicted median weekly household rental payment ($) 2023
[110.0, 140.0, 158.0]
predicted median weekly household rental payment ($) 2023
[110.0, 140.0, 158.0]
predicted median weekly household rental payment ($) 2023
[250.0, 293.3333333333333, 330.6666666666667]
predicted median weekly household rental payment ($) 2023
[150.0, 180.0, 215.0]
predicted median weekly household rental payment ($) 2023
[266.6666666666667, 313.0, 365.3333333333333]
predicted median weekly household rental payment ($) 2023
[240.0, 280.0, 330.0]
predicted median weekly household rental payment ($) 2023
[311.0, 356.0, 387.3333333333333]
predicted median weekly household rental payment ($) 2023
[171.66666666666666, 210.0, 253.3333333333333]
predicted median weekly household rental payment ($) 2023
[150.0, 180.0, 215.0]
predicted median weekly household rental payment ($) 2023
[218.75, 259.5, 302.0]
predicted median weekly household rental payment ($) 2023
[250.0, 295.0, 350.0]
predicted median weekly household rental payment ($) 2023
[200.0, 250.0, 300.0]
predicted median weekly household rental payment ($) 2023
[228.0, 252.5, 293.5]
predicted median weekly household rental payment ($) 2023
[335.3333333333333, 389.6666666666667, 418.3333333333333]
predicted median weekly household rental payment ($) 2023
[223.5, 263.75, 298.75]
predicted median weekly household rental payment ($) 2023
[297.0, 338.0, 387.5]
predicted median weekly household rental payment ($) 2023
[195.0, 230.0, 270.0]
predicted median weekly household rental payment ($) 2023
[176.0, 200.0, 250.0]
predicted median weekly household rental payment ($) 2023
[277.5, 328.0, 384.5]
predicted median weekly household rental payment ($) 2023
[311.0, 356.0, 387.3333333333333]
predicted median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
predicted median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
predicted median weekly household rental payment ($) 2023
[335.3333333333333, 389.6666666666667, 418.3333333333333]
predicted median weekly household rental payment ($) 2023
[335.3333333333333, 389.6666666666667, 418.3333333333333]
predicted median weekly household rental payment ($) 2023
[311.0, 356.0, 387.3333333333333]
predicted median weekly household rental payment ($) 2023
[207.5, 240.0, 275.0]
predicted median weekly household rental payment ($) 2023
[226.66666666666663, 275.0, 311.6666666666667]
predicted median weekly household rental payment ($) 2023
[170.0, 200.0, 235.0]
predicted median weekly household rental payment ($) 2023
[241.66666666666663, 286.6666666666667, 338.3333333333333]
predicted median weekly household rental payment ($) 2023
[171.66666666666666, 210.0, 253.3333333333333]
predicted median weekly household rental payment ($) 2023
[233.0, 260.0, 330.0]
predicted median weekly household rental payment ($) 2023
[325.0, 378.0, 414.5]
predicted median weekly household rental payment ($) 2023
[315.25, 355.0, 388.0]
predicted median weekly household rental payment ($) 2023
[165.0, 200.0, 250.0]
predicted median weekly household rental payment ($) 2023
[335.0, 385.5, 415.5]
predicted median weekly household rental payment ($) 2023
[200.0, 250.0, 280.0]
predicted median weekly household rental payment ($) 2023
[360.0, 391.0, 406.5]
predicted median weekly household rental payment ($) 2023
[176.0, 200.0, 250.0]
predicted median weekly household rental payment ($) 2023
[325.0, 378.0, 414.5]
predicted median weekly household rental payment ($) 2023
[325.0, 378.0, 414.5]
predicted median weekly household rental payment ($) 2023
[325.0, 378.0, 414.5]
predicted median weekly household rental payment ($) 2023
[250.0, 293.3333333333333, 330.6666666666667]
predicted median weekly household rental payment ($) 2023
[301.1, 476.7, 378.0]
predicted median weekly household rental payment ($) 2023
[226.66666666666663, 275.0, 311.6666666666667]
predicted median weekly household rental payment ($) 2023
[218.75, 259.5, 302.0]
predicted median weekly household rental payment ($) 2023
[100.0, 110.0, 150.0]
predicted median weekly household rental payment ($) 2023
[250.75, 294.5, 336.75]
predicted median weekly household rental payment ($) 2023
[250.0, 295.0, 350.0]
predicted median weekly household rental payment ($) 2023
[301.1, 476.7, 378.0]
predicted median weekly household rental payment ($) 2023
[207.5, 240.0, 275.0]
predicted median weekly household rental payment ($) 2023
[360.0, 391.0, 406.5]
predicted median weekly household rental payment ($) 2023
[286.0, 329.3333333333333, 374.3333333333333]
predicted median weekly household rental payment ($) 2023
[190.0, 235.0, 280.0]
predicted median weekly household rental payment ($) 2023
[311.0, 356.0, 387.3333333333333]
predicted median weekly household rental payment ($) 2023
[130.0, 150.0, 180.0]
predicted median weekly household rental payment ($) 2023
[180.0, 220.0, 260.0]
predicted median weekly household rental payment ($) 2023
[260.0, 300.0, 380.0]
predicted median weekly household rental payment ($) 2023
[311.0, 356.0, 387.3333333333333]
predicted median weekly household rental payment ($) 2023
[350.0, 400.0, 426.0]
predicted median weekly household rental payment ($) 2023
[310.57142857142856, 333.0, 375.2857142857143]
predicted median weekly household rental payment ($) 2023
[354.0, 397.0, 423.5]
predicted median weekly household rental payment ($) 2023
[335.3333333333333, 389.6666666666667, 418.3333333333333]
predicted median weekly household rental payment ($) 2023
[171.66666666666666, 210.0, 253.3333333333333]
predicted median weekly household rental payment ($) 2023
[130.0, 150.0, 182.0]
predicted median weekly household rental payment ($) 2023
[325.0, 378.0, 414.5]
predicted median weekly household rental payment ($) 2023
[190.0, 235.0, 280.0]
predicted median weekly household rental payment ($) 2023
[230.0, 275.0, 320.0]
predicted median weekly household rental payment ($) 2023
[266.6666666666667, 313.0, 365.3333333333333]
predicted median weekly household rental payment ($) 2023
[309.6, 334.4, 372.8]
predicted median weekly household rental payment ($) 2023
[175.0, 208.0, 250.0]
predicted median weekly household rental payment ($) 2023
[175.0, 208.0, 250.0]
predicted median weekly household rental payment ($) 2023
[207.5, 240.0, 275.0]
predicted median weekly household rental payment ($) 2023
[171.66666666666666, 210.0, 253.3333333333333]
predicted median weekly household rental payment ($) 2023
[205.0, 250.0, 290.0]
predicted median weekly household rental payment ($) 2023
[277.5, 328.0, 384.5]
predicted median weekly household rental payment ($) 2023
[354.0, 397.0, 423.5]
predicted median weekly household rental payment ($) 2023
[218.75, 259.5, 302.0]
predicted median weekly household rental payment ($) 2023
[218.75, 259.5, 302.0]
predicted median weekly household rental payment ($) 2023
[311.0, 356.0, 387.3333333333333]
predicted median weekly household rental payment ($) 2023
[170.0, 205.0, 245.0]
predicted median weekly household rental payment ($) 2023
[170.0, 205.0, 245.0]
predicted median weekly household rental payment ($) 2023
[150.0, 190.0, 250.0]
predicted median weekly household rental payment ($) 2023
[226.66666666666663, 275.0, 311.6666666666667]
predicted median weekly household rental payment ($) 2023
[335.3333333333333, 389.6666666666667, 418.3333333333333]
predicted median weekly household rental payment ($) 2023
[375.3333333333333, 414.6666666666667, 426.0]
predicted median weekly household rental payment ($) 2023
[207.5, 240.0, 275.0]
predicted median weekly household rental payment ($) 2023
[200.0, 250.0, 300.0]
predicted median weekly household rental payment ($) 2023
[150.0, 180.0, 215.0]
predicted median weekly household rental payment ($) 2023
[165.0, 200.0, 200.0]
predicted median weekly household rental payment ($) 2023
[315.4, 370.8, 422.8]
predicted median weekly household rental payment ($) 2023
[207.5, 240.0, 275.0]
predicted median weekly household rental payment ($) 2023
[160.0, 200.0, 240.0]
predicted median weekly household rental payment ($) 2023
[150.0, 180.0, 215.0]
predicted median weekly household rental payment ($) 2023
[205.0, 240.0, 286.5]
predicted median weekly household rental payment ($) 2023
[332.3333333333333, 392.0, 420.6666666666667]
predicted median weekly household rental payment ($) 2023
[325.0, 378.0, 414.5]
predicted median weekly household rental payment ($) 2023
[354.0, 397.0, 423.5]
predicted median weekly household rental payment ($) 2023
[150.0, 180.0, 215.0]
predicted median weekly household rental payment ($) 2023
[340.0, 405.0, 500.0]
predicted median weekly household rental payment ($) 2023
[190.0, 235.0, 280.0]
predicted median weekly household rental payment ($) 2023
[325.0, 378.0, 414.5]
predicted median weekly household rental payment ($) 2023
[150.0, 180.0, 215.0]
predicted median weekly household rental payment ($) 2023
[205.0, 240.0, 286.5]
predicted median weekly household rental payment ($) 2023
[150.0, 180.0, 215.0]
predicted median weekly household rental payment ($) 2023
[205.0, 240.0, 286.5]
predicted median weekly household rental payment ($) 2023
[288.0, 340.0, 390.0]
predicted median weekly household rental payment ($) 2023
[143.0, 170.0, 200.0]
predicted median weekly household rental payment ($) 2023
[228.0, 252.5, 293.5]
predicted median weekly household rental payment ($) 2023
[195.0, 230.0, 270.0]
predicted median weekly household rental payment ($) 2023
[170.0, 200.0, 240.0]
predicted median weekly household rental payment ($) 2023
[165.0, 200.0, 250.0]
predicted median weekly household rental payment ($) 2023
[154.5, 190.0, 220.0]
predicted median weekly household rental payment ($) 2023
[185.0, 231.0, 280.0]
predicted median weekly household rental payment ($) 2023
[288.3333333333333, 358.3333333333333, 410.0]
predicted median weekly household rental payment ($) 2023
[353.3333333333333, 405.0, 434.0]
predicted median weekly household rental payment ($) 2023
[325.0, 378.0, 414.5]
predicted median weekly household rental payment ($) 2023
[332.3333333333333, 392.0, 420.6666666666667]
predicted median weekly household rental payment ($) 2023
[207.5, 240.0, 275.0]
predicted median weekly household rental payment ($) 2023
[250.0, 293.3333333333333, 330.6666666666667]
predicted median weekly household rental payment ($) 2023
[354.0, 397.0, 423.5]
predicted median weekly household rental payment ($) 2023
[185.0, 231.0, 280.0]
predicted median weekly household rental payment ($) 2023
[468.0, 485.0, 471.3333333333333]
predicted median weekly household rental payment ($) 2023
[195.0, 230.0, 270.0]
predicted median weekly household rental payment ($) 2023
[200.0, 250.0, 285.0]
predicted median weekly household rental payment ($) 2023
[171.66666666666666, 210.0, 253.3333333333333]
predicted median weekly household rental payment ($) 2023
[180.0, 220.0, 260.0]
predicted median weekly household rental payment ($) 2023
[260.0, 312.0, 356.0]
predicted median weekly household rental payment ($) 2023
[267.0, 324.5, 378.75]
predicted median weekly household rental payment ($) 2023
[266.6666666666667, 313.0, 365.3333333333333]
predicted median weekly household rental payment ($) 2023
[180.0, 220.0, 260.0]
predicted median weekly household rental payment ($) 2023
[285.0, 337.0, 376.0]
predicted median weekly household rental payment ($) 2023
[190.0, 235.0, 280.0]
predicted median weekly household rental payment ($) 2023
[170.0, 200.0, 250.0]
predicted median weekly household rental payment ($) 2023
[110.0, 140.0, 158.0]
predicted median weekly household rental payment ($) 2023
[150.0, 180.0, 215.0]
predicted median weekly household rental payment ($) 2023
[190.0, 235.0, 280.0]
predicted median weekly household rental payment ($) 2023
[160.0, 200.0, 240.0]
predicted median weekly household rental payment ($) 2023
[195.0, 246.0, 280.0]
predicted median weekly household rental payment ($) 2023
[205.0, 253.0, 310.0]
predicted median weekly household rental payment ($) 2023
[287.0, 334.0, 380.0]
predicted median weekly household rental payment ($) 2023
[311.0, 356.0, 387.3333333333333]
predicted median weekly household rental payment ($) 2023
[283.0, 400.0, 425.0]
predicted median weekly household rental payment ($) 2023
[332.6666666666667, 377.0, 397.0]
predicted median weekly household rental payment ($) 2023
[380.0, 439.0, 453.0]
predicted median weekly household rental payment ($) 2023
[171.66666666666666, 210.0, 253.3333333333333]
predicted median weekly household rental payment ($) 2023
[195.0, 246.0, 280.0]
predicted median weekly household rental payment ($) 2023
[335.0, 385.5, 415.5]
predicted median weekly household rental payment ($) 2023
[190.0, 235.0, 280.0]
predicted median weekly household rental payment ($) 2023
[140.0, 180.0, 200.0]
predicted median weekly household rental payment ($) 2023
[190.0, 235.0, 280.0]
predicted median weekly household rental payment ($) 2023
[226.66666666666663, 275.0, 311.6666666666667]
predicted median weekly household rental payment ($) 2023
[311.0, 356.0, 387.3333333333333]
predicted median weekly household rental payment ($) 2023
[286.0, 329.3333333333333, 374.3333333333333]
predicted median weekly household rental payment ($) 2023
[286.0, 329.3333333333333, 374.3333333333333]
predicted median weekly household rental payment ($) 2023
[255.5, 300.5, 334.5]
predicted median weekly household rental payment ($) 2023
[335.3333333333333, 389.6666666666667, 418.3333333333333]
predicted median weekly household rental payment ($) 2023
[226.66666666666663, 275.0, 311.6666666666667]
predicted median weekly household rental payment ($) 2023
[335.3333333333333, 389.6666666666667, 418.3333333333333]
predicted median weekly household rental payment ($) 2023
[335.3333333333333, 389.6666666666667, 418.3333333333333]
predicted median weekly household rental payment ($) 2023
[223.5, 263.75, 298.75]
predicted median weekly household rental payment ($) 2023
[223.5, 263.75, 298.75]
predicted median weekly household rental payment ($) 2023
[354.0, 397.0, 423.5]
predicted median weekly household rental payment ($) 2023
[325.0, 378.0, 414.5]
predicted median weekly household rental payment ($) 2023
[266.6666666666667, 313.0, 365.3333333333333]
predicted median weekly household rental payment ($) 2023
[165.0, 200.0, 250.0]
predicted median weekly household rental payment ($) 2023
[233.0, 260.0, 330.0]
predicted median weekly household rental payment ($) 2023
[309.6, 334.4, 372.8]
predicted median weekly household rental payment ($) 2023
[267.0, 324.5, 378.75]
predicted median weekly household rental payment ($) 2023
[347.3333333333333, 383.3333333333333, 404.0]
predicted median weekly household rental payment ($) 2023
[180.0, 250.0, 280.0]
predicted median weekly household rental payment ($) 2023
[375.3333333333333, 414.6666666666667, 426.0]

In [106]:
# predict average family size (no. of persons) 2023
weekly_rent_2023_column = data.apply(lambda x:
    predict_2023_value([x["average family size (no. of persons) 2011"], 
     x["average family size (no. of persons) 2016"],
     x["average family size (no. of persons) 2021"]], 
    "predicted average family size (no. of persons) 2023"), axis=1)

data = pd.concat([data, weekly_rent_2023_column], axis=1)

data[["average family size (no. of persons) 2011", 
     "average family size (no. of persons) 2016",
     "average family size (no. of persons) 2021", 
     "predicted average family size (no. of persons) 2023"]]


data = data.drop(["average family size (no. of persons) 2011", 
     "average family size (no. of persons) 2016",
     "average family size (no. of persons) 2021"], axis=1)

[3.1333333333333333, 3.1333333333333333, 3.033333333333333]
predicted average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
predicted average family size (no. of persons) 2023
[2.7, 2.7, 2.7]
predicted average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
predicted average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
predicted average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[3.025, 3.025, 3.025]
predicted average family size (no. of persons) 2023
[3.04, 3.04, 2.96]
predicted average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
predicted average family size (no. of persons) 2023
[2.45, 2.45, 2.5]
predicted average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
predicted average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
predicted average family size (no. of persons) 2023
[3.0, 2.9, 2.9]
predicted average family size (no. of persons) 2023
[3.1333333333333333, 3.1666666666666665, 3.2]
predicted average family size (no. of persons) 2023
[3.1333333333333333, 3.1666666666666665, 3.2]
predicted average family size (no. of persons) 2023
[3.125, 3.075, 3.05]
predicted average family size (no. of persons) 2023
[2.833333333333333, 2.833333333333333, 2.766666666666667]
predicted average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
predicted average family size (no. of persons) 2023
[2.7, 2.7, 2.6]
predicted average family size (no. of persons) 2023
[3.0, 3.0, 3.0]
predicted average family size (no. of persons) 2023
[3.0, 2.9, 2.9]
predicted average family size (no. of persons) 2023
[3.04, 3.04, 2.96]
predicted average family size (no. of persons) 2023
[3.04, 3.04, 2.96]
predicted average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
predicted average family size (no. of persons) 2023
[2.833333333333333, 2.833333333333333, 2.766666666666667]
predicted average family size (no. of persons) 2023
[3.1333333333333333, 3.1666666666666665, 3.2]
predicted average family size (no. of persons) 2023
[2.966666666666667, 2.966666666666667, 2.9]
predicted average family size (no. of persons) 2023
[2.925, 2.975, 2.95]
predicted average family size (no. of persons) 2023
[3.05, 3.05, 3.05]
predicted average family size (no. of persons) 2023
[2.8, 2.8, 2.7]
predicted average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
predicted average family size (no. of persons) 2023
[2.925, 2.975, 2.95]
predicted average family size (no. of persons) 2023
[3.04, 3.04, 2.96]
predicted average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
predicted average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
predicted average family size (no. of persons) 2023
[3.0, 3.0, 3.0]
predicted average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
predicted average family size (no. of persons) 2023
[3.0, 3.0, 3.0]
predicted average family size (no. of persons) 2023
[3.1333333333333333, 3.1666666666666665, 3.2]
predicted average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
predicted average family size (no. of persons) 2023
[2.95, 2.9, 2.85]
predicted average family size (no. of persons) 2023
[3.25, 3.1500000000000004, 3.05]
predicted average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
predicted average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
predicted average family size (no. of persons) 2023
[2.9, 2.966666666666667, 2.9]
predicted average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[2.433333333333333, 2.4, 2.4]
predicted average family size (no. of persons) 2023
[2.9, 2.966666666666667, 2.9]
predicted average family size (no. of persons) 2023
[2.7, 2.7, 2.6]
predicted average family size (no. of persons) 2023
[2.8, 2.8, 2.75]
predicted average family size (no. of persons) 2023
[3.1, 3.1, 3.1]
predicted average family size (no. of persons) 2023
[3.0, 3.0, 3.0]
predicted average family size (no. of persons) 2023
[3.04, 3.04, 2.96]
predicted average family size (no. of persons) 2023
[3.04, 3.04, 2.96]
predicted average family size (no. of persons) 2023
[3.0, 2.9, 2.9]
predicted average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[3.025, 3.025, 3.025]
predicted average family size (no. of persons) 2023
[3.1333333333333333, 3.1666666666666665, 3.2]
predicted average family size (no. of persons) 2023
[3.025, 3.025, 3.025]
predicted average family size (no. of persons) 2023
[2.9, 2.9, 2.8]
predicted average family size (no. of persons) 2023
[2.9, 2.966666666666667, 2.9]
predicted average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[3.1333333333333333, 3.1666666666666665, 3.2]
predicted average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[2.9, 2.9333333333333336, 2.8666666666666667]
predicted average family size (no. of persons) 2023
[3.0, 2.9, 2.9]
predicted average family size (no. of persons) 2023
[2.833333333333333, 2.833333333333333, 2.766666666666667]
predicted average family size (no. of persons) 2023
[2.966666666666667, 2.9, 2.8666666666666667]
predicted average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[2.9625, 2.95, 2.9125]
predicted average family size (no. of persons) 2023
[2.9, 2.9, 2.85]
predicted average family size (no. of persons) 2023
[3.0, 3.0, 3.0]
predicted average family size (no. of persons) 2023
[2.95, 2.95, 2.85]
predicted average family size (no. of persons) 2023
[2.9, 2.966666666666667, 2.9]
predicted average family size (no. of persons) 2023
[2.925, 2.875, 2.9]
predicted average family size (no. of persons) 2023
[3.05, 3.1500000000000004, 3.25]
predicted average family size (no. of persons) 2023
[3.05, 3.0, 3.0]
predicted average family size (no. of persons) 2023
[2.8, 2.7, 2.7]
predicted average family size (no. of persons) 2023
[2.8, 2.8, 2.75]
predicted average family size (no. of persons) 2023
[2.833333333333333, 2.833333333333333, 2.766666666666667]
predicted average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
predicted average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
predicted average family size (no. of persons) 2023
[2.9, 2.966666666666667, 2.9]
predicted average family size (no. of persons) 2023
[2.9, 2.966666666666667, 2.9]
predicted average family size (no. of persons) 2023
[2.833333333333333, 2.833333333333333, 2.766666666666667]
predicted average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
predicted average family size (no. of persons) 2023
[3.033333333333333, 3.0, 2.9333333333333336]
predicted average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[2.8666666666666667, 2.8666666666666667, 2.833333333333333]
predicted average family size (no. of persons) 2023
[2.966666666666667, 2.9, 2.8666666666666667]
predicted average family size (no. of persons) 2023
[2.8, 2.7, 2.7]
predicted average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
predicted average family size (no. of persons) 2023
[3.35, 3.35, 3.3]
predicted average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[3.0, 3.0, 2.9]
predicted average family size (no. of persons) 2023
[3.0, 3.0, 2.9]
predicted average family size (no. of persons) 2023
[2.45, 2.45, 2.5]
predicted average family size (no. of persons) 2023
[2.8, 2.7, 2.7]
predicted average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
predicted average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
predicted average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
predicted average family size (no. of persons) 2023
[3.1333333333333333, 3.1666666666666665, 3.2]
predicted average family size (no. of persons) 2023
[3.2299999999999995, 3.24, 3.35]
predicted average family size (no. of persons) 2023
[3.033333333333333, 3.0, 2.9333333333333336]
predicted average family size (no. of persons) 2023
[2.9625, 2.95, 2.9125]
predicted average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[3.05, 3.05, 3.05]
predicted average family size (no. of persons) 2023
[2.9, 2.9, 2.85]
predicted average family size (no. of persons) 2023
[3.2299999999999995, 3.24, 3.35]
predicted average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
predicted average family size (no. of persons) 2023
[2.45, 2.45, 2.5]
predicted average family size (no. of persons) 2023
[3.0500000000000003, 3.0500000000000003, 2.983333333333333]
predicted average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
predicted average family size (no. of persons) 2023
[2.833333333333333, 2.833333333333333, 2.766666666666667]
predicted average family size (no. of persons) 2023
[2.9, 2.8, 2.7]
predicted average family size (no. of persons) 2023
[2.9, 2.9, 2.8]
predicted average family size (no. of persons) 2023
[2.9, 2.9, 2.8]
predicted average family size (no. of persons) 2023
[2.833333333333333, 2.833333333333333, 2.766666666666667]
predicted average family size (no. of persons) 2023
[3.1, 3.1, 3.0]
predicted average family size (no. of persons) 2023
[3.157142857142857, 3.2142857142857144, 3.2142857142857144]
predicted average family size (no. of persons) 2023
[3.1, 3.1, 3.0]
predicted average family size (no. of persons) 2023
[2.9, 2.966666666666667, 2.9]
predicted average family size (no. of persons) 2023
[2.966666666666667, 2.9, 2.8666666666666667]
predicted average family size (no. of persons) 2023
[2.8, 2.7, 2.8]
predicted average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
predicted average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
predicted average family size (no. of persons) 2023
[2.85, 2.8, 2.75]
predicted average family size (no. of persons) 2023
[2.9, 2.9333333333333336, 2.8666666666666667]
predicted average family size (no. of persons) 2023
[3.04, 3.04, 2.96]
predicted average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
predicted average family size (no. of persons) 2023
[2.966666666666667, 2.9, 2.8666666666666667]
predicted average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[2.8, 2.8, 2.75]
predicted average family size (no. of persons) 2023
[3.1, 3.1, 3.0]
predicted average family size (no. of persons) 2023
[2.9625, 2.95, 2.9125]
predicted average family size (no. of persons) 2023
[2.9625, 2.95, 2.9125]
predicted average family size (no. of persons) 2023
[2.833333333333333, 2.833333333333333, 2.766666666666667]
predicted average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
predicted average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
predicted average family size (no. of persons) 2023
[2.7, 2.7, 2.7]
predicted average family size (no. of persons) 2023
[3.033333333333333, 3.0, 2.9333333333333336]
predicted average family size (no. of persons) 2023
[2.9, 2.966666666666667, 2.9]
predicted average family size (no. of persons) 2023
[2.433333333333333, 2.4, 2.4]
predicted average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
predicted average family size (no. of persons) 2023
[3.0, 2.9, 2.9]
predicted average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[2.8, 2.8, 2.7]
predicted average family size (no. of persons) 2023
[3.14, 3.12, 3.06]
predicted average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
predicted average family size (no. of persons) 2023
[3.0, 3.0, 3.0]
predicted average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[2.9, 2.9, 2.85]
predicted average family size (no. of persons) 2023
[2.8000000000000003, 2.8000000000000003, 2.733333333333333]
predicted average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
predicted average family size (no. of persons) 2023
[3.1, 3.1, 3.0]
predicted average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[3.1, 3.1, 3.1]
predicted average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
predicted average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
predicted average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[2.9, 2.9, 2.85]
predicted average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[2.9, 2.9, 2.85]
predicted average family size (no. of persons) 2023
[2.8, 2.9, 2.9]
predicted average family size (no. of persons) 2023
[2.9, 2.9, 2.8]
predicted average family size (no. of persons) 2023
[2.95, 2.95, 2.85]
predicted average family size (no. of persons) 2023
[3.05, 3.0, 3.0]
predicted average family size (no. of persons) 2023
[3.0, 3.0, 2.9]
predicted average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[2.8, 2.8, 2.75]
predicted average family size (no. of persons) 2023
[2.766666666666667, 2.733333333333333, 2.7]
predicted average family size (no. of persons) 2023
[2.966666666666667, 3.0, 3.0]
predicted average family size (no. of persons) 2023
[2.7, 2.6333333333333333, 2.566666666666667]
predicted average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
predicted average family size (no. of persons) 2023
[2.8000000000000003, 2.8000000000000003, 2.733333333333333]
predicted average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
predicted average family size (no. of persons) 2023
[3.1333333333333333, 3.1666666666666665, 3.2]
predicted average family size (no. of persons) 2023
[3.1, 3.1, 3.0]
predicted average family size (no. of persons) 2023
[2.766666666666667, 2.733333333333333, 2.7]
predicted average family size (no. of persons) 2023
[2.3666666666666667, 2.4, 2.466666666666667]
predicted average family size (no. of persons) 2023
[3.05, 3.0, 3.0]
predicted average family size (no. of persons) 2023
[2.9, 2.9, 2.8]
predicted average family size (no. of persons) 2023
[2.966666666666667, 2.9, 2.8666666666666667]
predicted average family size (no. of persons) 2023
[2.9, 2.9, 2.8]
predicted average family size (no. of persons) 2023
[3.1, 3.2, 3.1]
predicted average family size (no. of persons) 2023
[2.925, 2.975, 2.95]
predicted average family size (no. of persons) 2023
[2.9, 2.9333333333333336, 2.8666666666666667]
predicted average family size (no. of persons) 2023
[2.9, 2.9, 2.8]
predicted average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
predicted average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
predicted average family size (no. of persons) 2023
[2.8, 2.8, 2.7]
predicted average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
predicted average family size (no. of persons) 2023
[3.0, 3.0, 3.0]
predicted average family size (no. of persons) 2023
[3.0, 2.9, 2.9]
predicted average family size (no. of persons) 2023
[2.6, 2.6, 2.5]
predicted average family size (no. of persons) 2023
[2.966666666666667, 2.966666666666667, 2.9]
predicted average family size (no. of persons) 2023
[2.833333333333333, 2.833333333333333, 2.766666666666667]
predicted average family size (no. of persons) 2023
[2.6, 2.5, 2.4]
predicted average family size (no. of persons) 2023
[2.7, 2.733333333333333, 2.6666666666666665]
predicted average family size (no. of persons) 2023
[2.55, 2.6, 2.5]
predicted average family size (no. of persons) 2023
[2.966666666666667, 2.9, 2.8666666666666667]
predicted average family size (no. of persons) 2023
[3.0, 2.9, 2.9]
predicted average family size (no. of persons) 2023
[3.0, 3.0, 2.9]
predicted average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
predicted average family size (no. of persons) 2023
[2.8, 2.7, 2.7]
predicted average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
predicted average family size (no. of persons) 2023
[3.033333333333333, 3.0, 2.9333333333333336]
predicted average family size (no. of persons) 2023
[2.833333333333333, 2.833333333333333, 2.766666666666667]
predicted average family size (no. of persons) 2023
[3.0500000000000003, 3.0500000000000003, 2.983333333333333]
predicted average family size (no. of persons) 2023
[3.0500000000000003, 3.0500000000000003, 2.983333333333333]
predicted average family size (no. of persons) 2023
[3.025, 3.025, 3.025]
predicted average family size (no. of persons) 2023
[2.9, 2.966666666666667, 2.9]
predicted average family size (no. of persons) 2023
[3.033333333333333, 3.0, 2.9333333333333336]
predicted average family size (no. of persons) 2023
[2.9, 2.966666666666667, 2.9]
predicted average family size (no. of persons) 2023
[2.9, 2.966666666666667, 2.9]
predicted average family size (no. of persons) 2023
[2.925, 2.875, 2.9]
predicted average family size (no. of persons) 2023
[2.925, 2.875, 2.9]
predicted average family size (no. of persons) 2023
[3.1, 3.1, 3.0]
predicted average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
predicted average family size (no. of persons) 2023
[2.9, 2.9333333333333336, 2.8666666666666667]
predicted average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[2.8, 2.7, 2.7]
predicted average family size (no. of persons) 2023
[3.04, 3.04, 2.96]
predicted average family size (no. of persons) 2023
[2.925, 2.975, 2.95]
predicted average family size (no. of persons) 2023
[2.8666666666666667, 2.8666666666666667, 2.833333333333333]
predicted average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
predicted average family size (no. of persons) 2023
[2.433333333333333, 2.4, 2.4]
predicted average family size (no. of persons) 2023
[2.9, 2.9333333333333336, 2.8666666666666667]
predicted average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
predicted average family size (no. of persons) 2023
[2.9, 2.9333333333333336, 2.8666666666666667]
predicted average family size (no. of persons) 2023
[3.05, 3.0, 3.0]
predicted average family size (no. of persons) 2023
[2.9, 2.9333333333333336, 2.8666666666666667]
predicted average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
predicted average family size (no. of persons) 2023
[2.6, 2.6, 2.5]
predicted average family size (no. of persons) 2023
[2.9625, 2.95, 2.9125]
predicted average family size (no. of persons) 2023
[3.2, 3.233333333333333, 3.2]
predicted average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[2.9625, 2.95, 2.9125]
predicted average family size (no. of persons) 2023
[2.55, 2.6, 2.5]
predicted average family size (no. of persons) 2023
[2.9, 2.9333333333333336, 2.8666666666666667]
predicted average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[3.1500000000000004, 3.2, 3.1]
predicted average family size (no. of persons) 2023
[2.8, 2.8, 2.75]
predicted average family size (no. of persons) 2023
[2.9625, 2.95, 2.9125]
predicted average family size (no. of persons) 2023
[3.033333333333333, 3.0500000000000003, 3.016666666666667]
predicted average family size (no. of persons) 2023
[3.033333333333333, 3.0, 2.9333333333333336]
predicted average family size (no. of persons) 2023
[3.075, 3.05, 3.0]
predicted average family size (no. of persons) 2023
[3.1, 3.2, 3.1]
predicted average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
predicted average family size (no. of persons) 2023
[2.9, 2.9, 2.85]
predicted average family size (no. of persons) 2023
[2.9, 2.9333333333333336, 2.8666666666666667]

In [107]:
# predict median weekly household rental payment ($) 2023
weekly_rent_2023_column = data.apply(lambda x:
    predict_2023_value([x["employment ratio 2011"], 
     x["employment ratio 2016"],
     x["employment ratio 2021"]], 
    "predicted employment ratio 2023"), axis=1)

data = pd.concat([data, weekly_rent_2023_column], axis=1)

data[["employment ratio 2011", 
     "employment ratio 2016",
     "employment ratio 2021", 
     "predicted employment ratio 2023"]]


data = data.drop(["employment ratio 2011", 
     "employment ratio 2016",
     "employment ratio 2021"], axis=1)

[0.9559454742700816, 0.9464455426724956, 0.9557909279300024]
predicted employment ratio 2023
[0.9526246472248354, 0.9422108866366872, 0.9598731245594604]
predicted employment ratio 2023
[0.9477260846837428, 0.9499287604315082, 0.96588274263001]
predicted employment ratio 2023
[0.9526246472248354, 0.9422108866366872, 0.9598731245594604]
predicted employment ratio 2023
[0.9526246472248354, 0.9422108866366872, 0.9598731245594604]
predicted employment ratio 2023
[0.8778321551567881, 0.8559662899827619, 0.8905660377358491]
predicted employment ratio 2023
[0.9007145859604876, 0.8874827955344854, 0.9205526770293608]
predicted employment ratio 2023
[0.9270833333333334, 0.9057836644591613, 0.9342460070524788]
predicted employment ratio 2023
[0.9526246472248354, 0.9422108866366872, 0.9598731245594604]
predicted employment ratio 2023
[0.9563015558107968, 0.9489363704819276, 0.9572294059137354]
predicted employment ratio 2023
[0.9526246472248354, 0.9422108866366872, 0.9598731245594604]
predicted employment ratio 2023
[0.9526246472248354, 0.9422108866366872, 0.9598731245594604]
predicted employment ratio 2023
[0.9472402597402596, 0.9407685639988442, 0.964783759929391]
predicted employment ratio 2023
[0.9064708257621644, 0.8844212044716913, 0.9158166615593398]
predicted employment ratio 2023
[0.9064708257621644, 0.8844212044716913, 0.9158166615593398]
predicted employment ratio 2023
[0.9015253390709648, 0.8782967437748637, 0.9024309514177484]
predicted employment ratio 2023
[0.8894287396937574, 0.8618365627632687, 0.9152577859199162]
predicted employment ratio 2023
[0.9299378062570676, 0.916991195394514, 0.941056988464339]
predicted employment ratio 2023
[0.9524111675126904, 0.95863309352518, 0.9608788853161844]
predicted employment ratio 2023
[0.9506731405870668, 0.9369350207380625, 0.9488488488488488]
predicted employment ratio 2023
[0.9534188785375286, 0.9560614081524615, 0.9635515633097254]
predicted employment ratio 2023
[0.9270833333333334, 0.9057836644591613, 0.9342460070524788]
predicted employment ratio 2023
[0.9270833333333334, 0.9057836644591613, 0.9342460070524788]
predicted employment ratio 2023
[0.9299378062570676, 0.916991195394514, 0.941056988464339]
predicted employment ratio 2023
[0.8894287396937574, 0.8618365627632687, 0.9152577859199162]
predicted employment ratio 2023
[0.9064708257621644, 0.8844212044716913, 0.9158166615593398]
predicted employment ratio 2023
[0.9294129647574846, 0.9226576113667844, 0.943661971830986]
predicted employment ratio 2023
[0.9220409454512588, 0.911015199849878, 0.9383140068691128]
predicted employment ratio 2023
[0.9391982026258512, 0.9184815588969052, 0.9426702079419575]
predicted employment ratio 2023
[0.9531825355076275, 0.9464186563020544, 0.9617983367983368]
predicted employment ratio 2023
[0.9526246472248354, 0.9422108866366872, 0.9598731245594604]
predicted employment ratio 2023
[0.9220409454512588, 0.911015199849878, 0.9383140068691128]
predicted employment ratio 2023
[0.9270833333333334, 0.9057836644591613, 0.9342460070524788]
predicted employment ratio 2023
[0.9526246472248354, 0.9422108866366872, 0.9598731245594604]
predicted employment ratio 2023
[0.9526246472248354, 0.9422108866366872, 0.9598731245594604]
predicted employment ratio 2023
[0.95220015576324, 0.9390619340818545, 0.9510106200753684]
predicted employment ratio 2023
[0.9526246472248354, 0.9422108866366872, 0.9598731245594604]
predicted employment ratio 2023
[0.9506731405870668, 0.9369350207380625, 0.9488488488488488]
predicted employment ratio 2023
[0.9064708257621644, 0.8844212044716913, 0.9158166615593398]
predicted employment ratio 2023
[0.9526246472248354, 0.9422108866366872, 0.9598731245594604]
predicted employment ratio 2023
[0.9391057312252964, 0.9154583983939326, 0.9435585020605626]
predicted employment ratio 2023
[0.9454344352955636, 0.9314657647884628, 0.9415957236190852]
predicted employment ratio 2023
[0.9428933006406708, 0.926487747957993, 0.951145146422747]
predicted employment ratio 2023
[0.9526246472248354, 0.9422108866366872, 0.9598731245594604]
predicted employment ratio 2023
[0.9317939808328196, 0.9078024992380372, 0.937645478961504]
predicted employment ratio 2023
[0.9381158849034292, 0.9399841017488076, 0.9573353293413174]
predicted employment ratio 2023
[0.9551004636785162, 0.946282716270196, 0.9596152795234713]
predicted employment ratio 2023
[0.9317939808328196, 0.9078024992380372, 0.937645478961504]
predicted employment ratio 2023
[0.9524111675126904, 0.95863309352518, 0.9608788853161844]
predicted employment ratio 2023
[0.92882096069869, 0.9128011011699932, 0.9424161656232568]
predicted employment ratio 2023
[0.9619354838709676, 0.9589455488331892, 0.9684786859601096]
predicted employment ratio 2023
[0.9299953639313862, 0.9289693593314764, 0.9555752998667258]
predicted employment ratio 2023
[0.9270833333333334, 0.9057836644591613, 0.9342460070524788]
predicted employment ratio 2023
[0.9270833333333334, 0.9057836644591613, 0.9342460070524788]
predicted employment ratio 2023
[0.9534188785375286, 0.9560614081524615, 0.9635515633097254]
predicted employment ratio 2023
[0.957586987852584, 0.949730312837109, 0.9692882340734592]
predicted employment ratio 2023
[0.9007145859604876, 0.8874827955344854, 0.9205526770293608]
predicted employment ratio 2023
[0.9064708257621644, 0.8844212044716913, 0.9158166615593398]
predicted employment ratio 2023
[0.9007145859604876, 0.8874827955344854, 0.9205526770293608]
predicted employment ratio 2023
[0.9548022598870056, 0.937807881773399, 0.9491634491634492]
predicted employment ratio 2023
[0.9317939808328196, 0.9078024992380372, 0.937645478961504]
predicted employment ratio 2023
[0.9628975265017669, 0.9579475308641976, 0.9651162790697676]
predicted employment ratio 2023
[0.9628975265017669, 0.9579475308641976, 0.9651162790697676]
predicted employment ratio 2023
[0.9064708257621644, 0.8844212044716913, 0.9158166615593398]
predicted employment ratio 2023
[0.8778321551567881, 0.8559662899827619, 0.8905660377358491]
predicted employment ratio 2023
[0.93388074151099, 0.9254752583500864, 0.9484721390053924]
predicted employment ratio 2023
[0.9472402597402596, 0.9407685639988442, 0.964783759929391]
predicted employment ratio 2023
[0.8894287396937574, 0.8618365627632687, 0.9152577859199162]
predicted employment ratio 2023
[0.9233449477351916, 0.9080666614505908, 0.9395245170876672]
predicted employment ratio 2023
[0.8778321551567881, 0.8559662899827619, 0.8905660377358491]
predicted employment ratio 2023
[0.9408712938495478, 0.9280320366132724, 0.9522613065326632]
predicted employment ratio 2023
[0.9486665504619138, 0.9464135021097048, 0.9585059058137751]
predicted employment ratio 2023
[0.9621716287215412, 0.9672865013774103, 0.9802268101192207]
predicted employment ratio 2023
[0.951369480156512, 0.9480355640994832, 0.968831312628024]
predicted employment ratio 2023
[0.9317939808328196, 0.9078024992380372, 0.937645478961504]
predicted employment ratio 2023
[0.9461356220106388, 0.931688080396896, 0.9548155579564748]
predicted employment ratio 2023
[0.9202390231228892, 0.9107581040940204, 0.9378521126760564]
predicted employment ratio 2023
[0.9376161950010328, 0.9238831037957675, 0.9471360235496136]
predicted employment ratio 2023
[0.9487461504619444, 0.9397363465160076, 0.962890625]
predicted employment ratio 2023
[0.92882096069869, 0.9128011011699932, 0.9424161656232568]
predicted employment ratio 2023
[0.8894287396937574, 0.8618365627632687, 0.9152577859199162]
predicted employment ratio 2023
[0.9526246472248354, 0.9422108866366872, 0.9598731245594604]
predicted employment ratio 2023
[0.9526246472248354, 0.9422108866366872, 0.9598731245594604]
predicted employment ratio 2023
[0.9317939808328196, 0.9078024992380372, 0.937645478961504]
predicted employment ratio 2023
[0.9317939808328196, 0.9078024992380372, 0.937645478961504]
predicted employment ratio 2023
[0.8894287396937574, 0.8618365627632687, 0.9152577859199162]
predicted employment ratio 2023
[0.9428933006406708, 0.926487747957993, 0.951145146422747]
predicted employment ratio 2023
[0.9438918073097128, 0.939769616199184, 0.9579878641900968]
predicted employment ratio 2023
[0.957586987852584, 0.949730312837109, 0.9692882340734592]
predicted employment ratio 2023
[0.942317892503536, 0.9380504742547424, 0.9551724137931036]
predicted employment ratio 2023
[0.9233449477351916, 0.9080666614505908, 0.9395245170876672]
predicted employment ratio 2023
[0.9502655721873492, 0.941627906976744, 0.9654691314963376]
predicted employment ratio 2023
[0.9360808893093662, 0.9206915180983252, 0.9381653244469128]
predicted employment ratio 2023
[0.9459654699125912, 0.9272727272727272, 0.9393717799567892]
predicted employment ratio 2023
[0.9595663639027248, 0.941415313225058, 0.959988649262202]
predicted employment ratio 2023
[0.9431249105737588, 0.9294377806071166, 0.9522892971711868]
predicted employment ratio 2023
[0.9612888789438352, 0.9628729281767956, 0.9781006958657388]
predicted employment ratio 2023
[0.9563015558107968, 0.9489363704819276, 0.9572294059137354]
predicted employment ratio 2023
[0.9487461504619444, 0.9397363465160076, 0.962890625]
predicted employment ratio 2023
[0.9360808893093662, 0.9206915180983252, 0.9381653244469128]
predicted employment ratio 2023
[0.9360808893093662, 0.9206915180983252, 0.9381653244469128]
predicted employment ratio 2023
[0.9360808893093662, 0.9206915180983252, 0.9381653244469128]
predicted employment ratio 2023
[0.9064708257621644, 0.8844212044716913, 0.9158166615593398]
predicted employment ratio 2023
[0.9360709539179256, 0.91520559056592, 0.930336549776418]
predicted employment ratio 2023
[0.9438918073097128, 0.939769616199184, 0.9579878641900968]
predicted employment ratio 2023
[0.9408712938495478, 0.9280320366132724, 0.9522613065326632]
predicted employment ratio 2023
[0.9708333333333332, 0.9601476014760147, 0.9672505712109672]
predicted employment ratio 2023
[0.8982264665757163, 0.875924365814846, 0.9170778074503236]
predicted employment ratio 2023
[0.9486665504619138, 0.9464135021097048, 0.9585059058137751]
predicted employment ratio 2023
[0.9360709539179256, 0.91520559056592, 0.930336549776418]
predicted employment ratio 2023
[0.9428933006406708, 0.926487747957993, 0.951145146422747]
predicted employment ratio 2023
[0.9563015558107968, 0.9489363704819276, 0.9572294059137354]
predicted employment ratio 2023
[0.9310075928586088, 0.9119868749359128, 0.936723797162158]
predicted employment ratio 2023
[0.924595371350779, 0.9144819851394924, 0.940755873340143]
predicted employment ratio 2023
[0.8894287396937574, 0.8618365627632687, 0.9152577859199162]
predicted employment ratio 2023
[0.9651438240270728, 0.9606272939606272, 0.972268626795857]
predicted employment ratio 2023
[0.945827766306328, 0.9463232639306776, 0.9658378378378378]
predicted employment ratio 2023
[0.9543514566709964, 0.94136160344542, 0.95613702439641]
predicted employment ratio 2023
[0.8894287396937574, 0.8618365627632687, 0.9152577859199162]
predicted employment ratio 2023
[0.9551960784313726, 0.945495201714339, 0.9580563079701224]
predicted employment ratio 2023
[0.9380326370406216, 0.9208532135840584, 0.9357430376018588]
predicted employment ratio 2023
[0.9528137690968864, 0.9390704095720204, 0.953658834548194]
predicted employment ratio 2023
[0.9317939808328196, 0.9078024992380372, 0.937645478961504]
predicted employment ratio 2023
[0.9233449477351916, 0.9080666614505908, 0.9395245170876672]
predicted employment ratio 2023
[0.952322738386308, 0.9495743287491814, 0.9645436638214052]
predicted employment ratio 2023
[0.9360808893093662, 0.9206915180983252, 0.9381653244469128]
predicted employment ratio 2023
[0.924595371350779, 0.9144819851394924, 0.940755873340143]
predicted employment ratio 2023
[0.9408642911296436, 0.9346036585365852, 0.9494517619474518]
predicted employment ratio 2023
[0.93388074151099, 0.9254752583500864, 0.9484721390053924]
predicted employment ratio 2023
[0.9270833333333334, 0.9057836644591613, 0.9342460070524788]
predicted employment ratio 2023
[0.9381158849034292, 0.9399841017488076, 0.9573353293413174]
predicted employment ratio 2023
[0.9381158849034292, 0.9399841017488076, 0.9573353293413174]
predicted employment ratio 2023
[0.9428933006406708, 0.926487747957993, 0.951145146422747]
predicted employment ratio 2023
[0.9233449477351916, 0.9080666614505908, 0.9395245170876672]
predicted employment ratio 2023
[0.9445034832920062, 0.931931818181818, 0.9582325092056811]
predicted employment ratio 2023
[0.92882096069869, 0.9128011011699932, 0.9424161656232568]
predicted employment ratio 2023
[0.9528137690968864, 0.9390704095720204, 0.953658834548194]
predicted employment ratio 2023
[0.9408712938495478, 0.9280320366132724, 0.9522613065326632]
predicted employment ratio 2023
[0.9408712938495478, 0.9280320366132724, 0.9522613065326632]
predicted employment ratio 2023
[0.8894287396937574, 0.8618365627632687, 0.9152577859199162]
predicted employment ratio 2023
[0.9616384915474644, 0.947652733118971, 0.9671833373698232]
predicted employment ratio 2023
[0.9616384915474644, 0.947652733118971, 0.9671833373698232]
predicted employment ratio 2023
[0.9578090303478904, 0.9551094890510948, 0.9639519359145527]
predicted employment ratio 2023
[0.9438918073097128, 0.939769616199184, 0.9579878641900968]
predicted employment ratio 2023
[0.9317939808328196, 0.9078024992380372, 0.937645478961504]
predicted employment ratio 2023
[0.9551004636785162, 0.946282716270196, 0.9596152795234713]
predicted employment ratio 2023
[0.9428933006406708, 0.926487747957993, 0.951145146422747]
predicted employment ratio 2023
[0.9525972182798752, 0.9501661129568106, 0.969188376753507]
predicted employment ratio 2023
[0.8778321551567881, 0.8559662899827619, 0.8905660377358491]
predicted employment ratio 2023
[0.9406340057636888, 0.9334451901565995, 0.9526411657559198]
predicted employment ratio 2023
[0.9591309904153354, 0.9489196952666415, 0.9607870995240464]
predicted employment ratio 2023
[0.9428933006406708, 0.926487747957993, 0.951145146422747]
predicted employment ratio 2023
[0.9362047947988622, 0.9334094368340944, 0.94794231445656]
predicted employment ratio 2023
[0.8778321551567881, 0.8559662899827619, 0.8905660377358491]
predicted employment ratio 2023
[0.9368307462438782, 0.92480444107999, 0.950390625]
predicted employment ratio 2023
[0.9273091193126344, 0.9175287714487516, 0.943300624442462]
predicted employment ratio 2023
[0.9360808893093662, 0.9206915180983252, 0.9381653244469128]
predicted employment ratio 2023
[0.9528137690968864, 0.9390704095720204, 0.953658834548194]
predicted employment ratio 2023
[0.8778321551567881, 0.8559662899827619, 0.8905660377358491]
predicted employment ratio 2023
[0.9619354838709676, 0.9589455488331892, 0.9684786859601096]
predicted employment ratio 2023
[0.924595371350779, 0.9144819851394924, 0.940755873340143]
predicted employment ratio 2023
[0.9360808893093662, 0.9206915180983252, 0.9381653244469128]
predicted employment ratio 2023
[0.8778321551567881, 0.8559662899827619, 0.8905660377358491]
predicted employment ratio 2023
[0.9368307462438782, 0.92480444107999, 0.950390625]
predicted employment ratio 2023
[0.8778321551567881, 0.8559662899827619, 0.8905660377358491]
predicted employment ratio 2023
[0.9368307462438782, 0.92480444107999, 0.950390625]
predicted employment ratio 2023
[0.948520608859244, 0.9427409261576972, 0.959119496855346]
predicted employment ratio 2023
[0.9548022598870056, 0.937807881773399, 0.9491634491634492]
predicted employment ratio 2023
[0.951369480156512, 0.9480355640994832, 0.968831312628024]
predicted employment ratio 2023
[0.9376161950010328, 0.9238831037957675, 0.9471360235496136]
predicted employment ratio 2023
[0.9497716894977168, 0.9490017361111112, 0.96192996742671]
predicted employment ratio 2023
[0.9595663639027248, 0.941415313225058, 0.959988649262202]
predicted employment ratio 2023
[0.9334715025906736, 0.9130076272933416, 0.9420146447654858]
predicted employment ratio 2023
[0.9489653973222048, 0.9443376514834936, 0.958998575818904]
predicted employment ratio 2023
[0.958312405826218, 0.9487411233053584, 0.9636959737715404]
predicted employment ratio 2023
[0.9418256345577802, 0.9417618553132572, 0.954497072911123]
predicted employment ratio 2023
[0.9360808893093662, 0.9206915180983252, 0.9381653244469128]
predicted employment ratio 2023
[0.9273091193126344, 0.9175287714487516, 0.943300624442462]
predicted employment ratio 2023
[0.9428933006406708, 0.926487747957993, 0.951145146422747]
predicted employment ratio 2023
[0.9064708257621644, 0.8844212044716913, 0.9158166615593398]
predicted employment ratio 2023
[0.9528137690968864, 0.9390704095720204, 0.953658834548194]
predicted employment ratio 2023
[0.9489653973222048, 0.9443376514834936, 0.958998575818904]
predicted employment ratio 2023
[0.9482331980599822, 0.928776726253067, 0.9450841452612933]
predicted employment ratio 2023
[0.9376161950010328, 0.9238831037957675, 0.9471360235496136]
predicted employment ratio 2023
[0.9559270516717324, 0.9514146052436676, 0.9630276956171012]
predicted employment ratio 2023
[0.9233449477351916, 0.9080666614505908, 0.9395245170876672]
predicted employment ratio 2023
[0.945827766306328, 0.9463232639306776, 0.9658378378378378]
predicted employment ratio 2023
[0.8947056733388606, 0.8825068119891009, 0.9189426453374951]
predicted employment ratio 2023
[0.9220409454512588, 0.911015199849878, 0.9383140068691128]
predicted employment ratio 2023
[0.93388074151099, 0.9254752583500864, 0.9484721390053924]
predicted employment ratio 2023
[0.945827766306328, 0.9463232639306776, 0.9658378378378378]
predicted employment ratio 2023
[0.9509885166331242, 0.9409980542520316, 0.9562625303366044]
predicted employment ratio 2023
[0.924595371350779, 0.9144819851394924, 0.940755873340143]
predicted employment ratio 2023
[0.9439472444653793, 0.9515377446411928, 0.9747215081405312]
predicted employment ratio 2023
[0.9628975265017669, 0.9579475308641976, 0.9651162790697676]
predicted employment ratio 2023
[0.8778321551567881, 0.8559662899827619, 0.8905660377358491]
predicted employment ratio 2023
[0.924595371350779, 0.9144819851394924, 0.940755873340143]
predicted employment ratio 2023
[0.9362047947988622, 0.9334094368340944, 0.94794231445656]
predicted employment ratio 2023
[0.9449416047322918, 0.932848264362589, 0.9488365370718312]
predicted employment ratio 2023
[0.9482758620689656, 0.9460562103354488, 0.9522130826478652]
predicted employment ratio 2023
[0.9294129647574846, 0.9226576113667844, 0.943661971830986]
predicted employment ratio 2023
[0.8894287396937574, 0.8618365627632687, 0.9152577859199162]
predicted employment ratio 2023
[0.9331084879145588, 0.9296135646687698, 0.951219512195122]
predicted employment ratio 2023
[0.9532624633431084, 0.9472393909050102, 0.9569686750113496]
predicted employment ratio 2023
[0.9022911051212938, 0.8650591583046279, 0.9109944207417132]
predicted employment ratio 2023
[0.9233449477351916, 0.9080666614505908, 0.9395245170876672]
predicted employment ratio 2023
[0.9449416047322918, 0.932848264362589, 0.9488365370718312]
predicted employment ratio 2023
[0.9431249105737588, 0.9294377806071166, 0.9522892971711868]
predicted employment ratio 2023
[0.924595371350779, 0.9144819851394924, 0.940755873340143]
predicted employment ratio 2023
[0.9424514200298952, 0.9270913277052956, 0.9567068843151172]
predicted employment ratio 2023
[0.924595371350779, 0.9144819851394924, 0.940755873340143]
predicted employment ratio 2023
[0.9438918073097128, 0.939769616199184, 0.9579878641900968]
predicted employment ratio 2023
[0.8894287396937574, 0.8618365627632687, 0.9152577859199162]
predicted employment ratio 2023
[0.9310075928586088, 0.9119868749359128, 0.936723797162158]
predicted employment ratio 2023
[0.9310075928586088, 0.9119868749359128, 0.936723797162158]
predicted employment ratio 2023
[0.9007145859604876, 0.8874827955344854, 0.9205526770293608]
predicted employment ratio 2023
[0.9317939808328196, 0.9078024992380372, 0.937645478961504]

In [108]:
print(list(data.columns))

['property type', 'beds', 'baths', 'parking', 'weekly rent amount', 'postcode', 'distance primary school', 'distance secondary school', 'is closest school good', 'distance university campus', 'distance to closest hospital', 'offence count 2023', 'estimated resident population (no.) 2011', 'total dwellings (no.) 2017', 'estimated resident population (no.) 2016', 'total dwellings (no.) 2019', 'estimated resident population (no.) 2021', 'total dwellings (no.) 2021', 'total_supermarkets', 'major_supermarkets', 'city_centre', 'closest_city_centre', 'coastal', 'closest_cc_dist', 'dist_to_melb', 'predicted median equivalised total household income (weekly) ($) 2023', 'predicted median weekly household rental payment ($) 2023', 'predicted average family size (no. of persons) 2023', 'predicted employment ratio 2023']

In [109]:
data.isna().any()

property type                                                            False
beds                                                                     False
baths                                                                    False
parking                                                                  False
weekly rent amount                                                       False
postcode                                                                 False
distance primary school                                                  False
distance secondary school                                                False
is closest school good                                                   False
distance university campus                                               False
distance to closest hospital                                             False
offence count 2023                                                       False
estimated resident population (no.) 2011                                 False
total dwellings (no.) 2017                                               False
estimated resident population (no.) 2016                                 False
total dwellings (no.) 2019                                               False
estimated resident population (no.) 2021                                 False
total dwellings (no.) 2021                                               False
total_supermarkets                                                        True
major_supermarkets                                                        True
city_centre                                                               True
closest_city_centre                                                       True
coastal                                                                   True
closest_cc_dist                                                           True
dist_to_melb                                                              True
predicted median equivalised total household income (weekly) ($) 2023    False
predicted median weekly household rental payment ($) 2023                False
predicted average family size (no. of persons) 2023                      False
predicted employment ratio 2023                                          False
dtype: bool

In [110]:
# drop columns with missing values
data = data.drop(["total_supermarkets", "major_supermarkets"], axis=1)

In [111]:
list(data.columns[data.isna().any()])

['city_centre',
 'closest_city_centre',
 'coastal',
 'closest_cc_dist',
 'dist_to_melb']

In [112]:
print(len(data))
data = data.dropna()
print(len(data))

11345
11235

In [113]:
data[data.isna().any(axis=1)]

Empty DataFrame
Columns: [property type, beds, baths, parking, weekly rent amount, postcode, distance primary school, distance secondary school, is closest school good, distance university campus, distance to closest hospital, offence count 2023, estimated resident population (no.) 2011, total dwellings (no.) 2017, estimated resident population (no.) 2016, total dwellings (no.) 2019, estimated resident population (no.) 2021, total dwellings (no.) 2021, city_centre, closest_city_centre, coastal, closest_cc_dist, dist_to_melb, predicted median equivalised total household income (weekly) ($) 2023, predicted median weekly household rental payment ($) 2023, predicted average family size (no. of persons) 2023, predicted employment ratio 2023]
Index: []

[0 rows x 27 columns]

In [114]:
# ensure categorical variables behave as categorical variables
data["postcode"] = data["postcode"].astype("category")

In [115]:
# one hot encode categorical variables
#data = pd.get_dummies(data, columns=["postcode", "closest university campus", 
                                     #"property type", "closest hospital", "closest_city_centre"])

data = pd.get_dummies(data, columns=["postcode", 
                                     "property type", "closest_city_centre"])

#data = pd.get_dummies(data, columns=["postcode", "closest primary school", "closest university campus", "closest secondary school", 
                                     #"property type", "closest hospital"])

data

,beds,baths,parking,weekly rent amount,distance primary school,distance secondary school,is closest school good,distance university campus,distance to closest hospital,offence count 2023,...,closest_city_centre_Horsham,closest_city_centre_Melbourne,closest_city_centre_Morwell,closest_city_centre_Sale,closest_city_centre_Shepparton,closest_city_centre_Swan Hill,closest_city_centre_Traralgon,closest_city_centre_Wangaratta,closest_city_centre_Warrnambool,closest_city_centre_Wodonga
0,1,2,6,120,0.586504,2.491226,True,7.430317,2.104719,29.0,...,False,True,False,False,False,False,False,False,False,False
1,9,2,2,130,1.372612,2.438191,False,0.675843,6.688022,121.0,...,False,False,False,False,False,False,False,False,False,False
2,1,1,0,140,4.858273,3.301447,True,47.278807,10.766412,17.0,...,False,False,False,False,False,False,False,False,False,False
3,1,2,6,140,1.114181,1.998214,False,1.502495,6.057051,121.0,...,False,False,False,False,False,False,False,False,False,False
4,1,4,3,150,0.215009,1.989564,False,1.862509,5.472987,121.0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11340,4,4,2,4400,0.311431,0.891118,True,11.507926,0.931372,37.0,...,False,True,False,False,False,False,False,False,False,False
11341,4,3,0,4700,3.095969,14.695112,False,44.215772,28.018349,13.0,...,False,False,False,False,False,False,False,False,False,False
11342,3,3,4,5000,1.327110,0.766691,False,0.615756,1.652282,67.0,...,False,True,False,False,False,False,False,False,False,False
11343,6,7,8,9950,0.414506,1.204451,True,10.386190,1.204835,14.0,...,False,True,False,False,False,False,False,False,False,False
11344,6,7,8,9950,0.414506,1.204451,True,10.386190,1.204835,14.0,...,False,True,False,False,False,False,False,False,False,False

# Linear Regression Model

In [116]:
data["city_centre"] = data["city_centre"].astype(bool)
data["coastal"] = data["coastal"].astype(bool)

In [117]:
y = data["weekly rent amount"]
X = data.drop(["weekly rent amount"], axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [118]:
type_dict = dict(data.dtypes)
print(str(type(type_dict["is closest school good"])))

def get_key_from_value(my_dict, search_value):
    # Iterate through the dictionary items
    for key, value in my_dict.items():
        if str(value) == search_value:
            return key  # Return the key if the value matches the search_value
    # If the search_value is not found, you can return a default value or raise an exception
    return None  # Return None (or raise an exception) if the search_value is not found

# Example dictionary
my_dict = {'apple': 1, 'banana': 2, 'cherry': 3, 'date': 2}

# Find the key for a specific value
search_value = "object"
key = get_key_from_value(type_dict, search_value)

if key is not None:
    print(f"The key for value {search_value} is: {key}")
else:
    print(f"Value {search_value} not found in the dictionary.")

<class 'numpy.dtype[bool_]'>
Value object not found in the dictionary.

In [119]:
data["city_centre"] = data["city_centre"].astype(bool)
data.dtypes
# Find the key for a specific value
search_value = "object"
key = get_key_from_value(type_dict, search_value)

if key is not None:
    print(f"The key for value {search_value} is: {key}")
else:
    print(f"Value {search_value} not found in the dictionary.")

Value object not found in the dictionary.

In [120]:
data = data.drop(["city_centre"], axis=1)

In [121]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [122]:
X_train_scaled

array([[ 1.27547098,  2.34696224,  0.62099055, ..., -0.06933365,
        -0.09234624, -0.08666238],
       [ 0.33395216,  0.7379236 ,  0.62099055, ..., -0.06933365,
        -0.09234624, -0.08666238],
       [-0.60756666,  0.7379236 , -0.35718384, ..., -0.06933365,
        -0.09234624, -0.08666238],
       ...,
       [ 0.33395216,  0.7379236 ,  0.62099055, ..., -0.06933365,
        -0.09234624, -0.08666238],
       [-0.60756666,  0.7379236 , -0.35718384, ..., -0.06933365,
        -0.09234624, -0.08666238],
       [ 1.27547098,  0.7379236 ,  0.62099055, ..., -0.06933365,
        -0.09234624, -0.08666238]])

In [123]:
print(dict(data.isna().any()))

{'beds': False, 'baths': False, 'parking': False, 'weekly rent amount': False, 'distance primary school': False, 'distance secondary school': False, 'is closest school good': False, 'distance university campus': False, 'distance to closest hospital': False, 'offence count 2023': False, 'estimated resident population (no.) 2011': False, 'total dwellings (no.) 2017': False, 'estimated resident population (no.) 2016': False, 'total dwellings (no.) 2019': False, 'estimated resident population (no.) 2021': False, 'total dwellings (no.) 2021': False, 'coastal': False, 'closest_cc_dist': False, 'dist_to_melb': False, 'predicted median equivalised total household income (weekly) ($) 2023': False, 'predicted median weekly household rental payment ($) 2023': False, 'predicted average family size (no. of persons) 2023': False, 'predicted employment ratio 2023': False, 'postcode_3000': False, 'postcode_3002': False, 'postcode_3003': False, 'postcode_3004': False, 'postcode_3006': False, 'postcode_3008': False, 'postcode_3011': False, 'postcode_3012': False, 'postcode_3013': False, 'postcode_3015': False, 'postcode_3016': False, 'postcode_3018': False, 'postcode_3019': False, 'postcode_3020': False, 'postcode_3021': False, 'postcode_3022': False, 'postcode_3023': False, 'postcode_3024': False, 'postcode_3025': False, 'postcode_3026': False, 'postcode_3027': False, 'postcode_3028': False, 'postcode_3029': False, 'postcode_3030': False, 'postcode_3031': False, 'postcode_3032': False, 'postcode_3033': False, 'postcode_3034': False, 'postcode_3036': False, 'postcode_3037': False, 'postcode_3038': False, 'postcode_3039': False, 'postcode_3040': False, 'postcode_3041': False, 'postcode_3042': False, 'postcode_3043': False, 'postcode_3044': False, 'postcode_3046': False, 'postcode_3047': False, 'postcode_3048': False, 'postcode_3049': False, 'postcode_3051': False, 'postcode_3052': False, 'postcode_3053': False, 'postcode_3054': False, 'postcode_3055': False, 'postcode_3056': False, 'postcode_3057': False, 'postcode_3058': False, 'postcode_3059': False, 'postcode_3060': False, 'postcode_3061': False, 'postcode_3064': False, 'postcode_3065': False, 'postcode_3066': False, 'postcode_3067': False, 'postcode_3068': False, 'postcode_3070': False, 'postcode_3071': False, 'postcode_3072': False, 'postcode_3073': False, 'postcode_3074': False, 'postcode_3075': False, 'postcode_3076': False, 'postcode_3078': False, 'postcode_3079': False, 'postcode_3081': False, 'postcode_3082': False, 'postcode_3083': False, 'postcode_3084': False, 'postcode_3085': False, 'postcode_3087': False, 'postcode_3088': False, 'postcode_3089': False, 'postcode_3091': False, 'postcode_3093': False, 'postcode_3094': False, 'postcode_3095': False, 'postcode_3097': False, 'postcode_3101': False, 'postcode_3102': False, 'postcode_3103': False, 'postcode_3104': False, 'postcode_3105': False, 'postcode_3106': False, 'postcode_3107': False, 'postcode_3108': False, 'postcode_3109': False, 'postcode_3111': False, 'postcode_3113': False, 'postcode_3115': False, 'postcode_3116': False, 'postcode_3121': False, 'postcode_3122': False, 'postcode_3123': False, 'postcode_3124': False, 'postcode_3125': False, 'postcode_3126': False, 'postcode_3127': False, 'postcode_3128': False, 'postcode_3129': False, 'postcode_3130': False, 'postcode_3131': False, 'postcode_3132': False, 'postcode_3133': False, 'postcode_3134': False, 'postcode_3135': False, 'postcode_3136': False, 'postcode_3137': False, 'postcode_3138': False, 'postcode_3139': False, 'postcode_3140': False, 'postcode_3141': False, 'postcode_3142': False, 'postcode_3143': False, 'postcode_3144': False, 'postcode_3145': False, 'postcode_3146': False, 'postcode_3147': False, 'postcode_3148': False, 'postcode_3149': False, 'postcode_3150': False, 'postcode_3151': False, 'postcode_3152': False, 'postcode_3153': False, 'postcode_3154': False, 'postcode_3155': False, 'postcode_3156': False, 'postcode_3158': False, 'postcode_3160': False, 'postcode_3161': False, 'postcode_3162': False, 'postcode_3163': False, 'postcode_3165': False, 'postcode_3166': False, 'postcode_3167': False, 'postcode_3168': False, 'postcode_3169': False, 'postcode_3170': False, 'postcode_3171': False, 'postcode_3172': False, 'postcode_3173': False, 'postcode_3174': False, 'postcode_3175': False, 'postcode_3177': False, 'postcode_3178': False, 'postcode_3179': False, 'postcode_3180': False, 'postcode_3181': False, 'postcode_3182': False, 'postcode_3183': False, 'postcode_3184': False, 'postcode_3185': False, 'postcode_3186': False, 'postcode_3187': False, 'postcode_3188': False, 'postcode_3189': False, 'postcode_3190': False, 'postcode_3191': False, 'postcode_3192': False, 'postcode_3193': False, 'postcode_3194': False, 'postcode_3195': False, 'postcode_3196': False, 'postcode_3197': False, 'postcode_3198': False, 'postcode_3199': False, 'postcode_3200': False, 'postcode_3201': False, 'postcode_3202': False, 'postcode_3204': False, 'postcode_3205': False, 'postcode_3206': False, 'postcode_3207': False, 'postcode_3212': False, 'postcode_3213': False, 'postcode_3214': False, 'postcode_3215': False, 'postcode_3216': False, 'postcode_3217': False, 'postcode_3218': False, 'postcode_3219': False, 'postcode_3220': False, 'postcode_3222': False, 'postcode_3223': False, 'postcode_3224': False, 'postcode_3225': False, 'postcode_3226': False, 'postcode_3227': False, 'postcode_3228': False, 'postcode_3230': False, 'postcode_3231': False, 'postcode_3233': False, 'postcode_3235': False, 'postcode_3241': False, 'postcode_3242': False, 'postcode_3249': False, 'postcode_3250': False, 'postcode_3254': False, 'postcode_3260': False, 'postcode_3264': False, 'postcode_3266': False, 'postcode_3272': False, 'postcode_3277': False, 'postcode_3280': False, 'postcode_3284': False, 'postcode_3289': False, 'postcode_3294': False, 'postcode_3300': False, 'postcode_3304': False, 'postcode_3305': False, 'postcode_3318': False, 'postcode_3321': False, 'postcode_3328': False, 'postcode_3331': False, 'postcode_3335': False, 'postcode_3337': False, 'postcode_3338': False, 'postcode_3340': False, 'postcode_3342': False, 'postcode_3345': False, 'postcode_3350': False, 'postcode_3351': False, 'postcode_3352': False, 'postcode_3355': False, 'postcode_3356': False, 'postcode_3357': False, 'postcode_3363': False, 'postcode_3373': False, 'postcode_3377': False, 'postcode_3380': False, 'postcode_3393': False, 'postcode_3400': False, 'postcode_3414': False, 'postcode_3418': False, 'postcode_3429': False, 'postcode_3431': False, 'postcode_3434': False, 'postcode_3435': False, 'postcode_3437': False, 'postcode_3438': False, 'postcode_3444': False, 'postcode_3450': False, 'postcode_3451': False, 'postcode_3453': False, 'postcode_3458': False, 'postcode_3460': False, 'postcode_3461': False, 'postcode_3463': False, 'postcode_3464': False, 'postcode_3465': False, 'postcode_3472': False, 'postcode_3477': False, 'postcode_3480': False, 'postcode_3490': False, 'postcode_3496': False, 'postcode_3498': False, 'postcode_3500': False, 'postcode_3501': False, 'postcode_3505': False, 'postcode_3515': False, 'postcode_3523': False, 'postcode_3550': False, 'postcode_3551': False, 'postcode_3555': False, 'postcode_3556': False, 'postcode_3561': False, 'postcode_3564': False, 'postcode_3568': False, 'postcode_3579': False, 'postcode_3585': False, 'postcode_3608': False, 'postcode_3612': False, 'postcode_3616': False, 'postcode_3620': False, 'postcode_3629': False, 'postcode_3630': False, 'postcode_3631': False, 'postcode_3638': False, 'postcode_3640': False, 'postcode_3641': False, 'postcode_3644': False, 'postcode_3658': False, 'postcode_3660': False, 'postcode_3664': False, 'postcode_3666': False, 'postcode_3669': False, 'postcode_3672': False, 'postcode_3673': False, 'postcode_3675': False, 'postcode_3677': False, 'postcode_3678': False, 'postcode_3685': False, 'postcode_3690': False, 'postcode_3691': False, 'postcode_3699': False, 'postcode_3700': False, 'postcode_3714': False, 'postcode_3717': False, 'postcode_3720': False, 'postcode_3722': False, 'postcode_3723': False, 'postcode_3730': False, 'postcode_3732': False, 'postcode_3733': False, 'postcode_3735': False, 'postcode_3737': False, 'postcode_3741': False, 'postcode_3747': False, 'postcode_3749': False, 'postcode_3750': False, 'postcode_3751': False, 'postcode_3752': False, 'postcode_3753': False, 'postcode_3754': False, 'postcode_3756': False, 'postcode_3757': False, 'postcode_3758': False, 'postcode_3764': False, 'postcode_3765': False, 'postcode_3775': False, 'postcode_3777': False, 'postcode_3781': False, 'postcode_3782': False, 'postcode_3783': False, 'postcode_3786': False, 'postcode_3787': False, 'postcode_3788': False, 'postcode_3792': False, 'postcode_3796': False, 'postcode_3799': False, 'postcode_3802': False, 'postcode_3803': False, 'postcode_3804': False, 'postcode_3805': False, 'postcode_3806': False, 'postcode_3807': False, 'postcode_3808': False, 'postcode_3809': False, 'postcode_3810': False, 'postcode_3812': False, 'postcode_3813': False, 'postcode_3815': False, 'postcode_3816': False, 'postcode_3818': False, 'postcode_3820': False, 'postcode_3823': False, 'postcode_3824': False, 'postcode_3825': False, 'postcode_3831': False, 'postcode_3835': False, 'postcode_3840': False, 'postcode_3842': False, 'postcode_3844': False, 'postcode_3847': False, 'postcode_3850': False, 'postcode_3851': False, 'postcode_3854': False, 'postcode_3858': False, 'postcode_3860': False, 'postcode_3869': False, 'postcode_3870': False, 'postcode_3871': False, 'postcode_3875': False, 'postcode_3878': False, 'postcode_3880': False, 'postcode_3882': False, 'postcode_3885': False, 'postcode_3888': False, 'postcode_3904': False, 'postcode_3909': False, 'postcode_3910': False, 'postcode_3911': False, 'postcode_3912': False, 'postcode_3913': False, 'postcode_3915': False, 'postcode_3916': False, 'postcode_3918': False, 'postcode_3919': False, 'postcode_3922': False, 'postcode_3923': False, 'postcode_3925': False, 'postcode_3926': False, 'postcode_3927': False, 'postcode_3929': False, 'postcode_3930': False, 'postcode_3931': False, 'postcode_3934': False, 'postcode_3936': False, 'postcode_3937': False, 'postcode_3938': False, 'postcode_3939': False, 'postcode_3940': False, 'postcode_3941': False, 'postcode_3942': False, 'postcode_3943': False, 'postcode_3944': False, 'postcode_3950': False, 'postcode_3953': False, 'postcode_3956': False, 'postcode_3960': False, 'postcode_3962': False, 'postcode_3971': False, 'postcode_3975': False, 'postcode_3976': False, 'postcode_3977': False, 'postcode_3978': False, 'postcode_3980': False, 'postcode_3981': False, 'postcode_3984': False, 'postcode_3987': False, 'postcode_3988': False, 'postcode_3991': False, 'postcode_3992': False, 'postcode_3995': False, 'postcode_3996': False, 'property type_Acreage / Semi-Rural': False, 'property type_Apartment / Unit / Flat': False, 'property type_Duplex': False, 'property type_House': False, 'property type_New Apartments / Off the Plan': False, 'property type_New House & Land': False, 'property type_Penthouse': False, 'property type_Retirement': False, 'property type_Semi-Detached': False, 'property type_Studio': False, 'property type_Terrace': False, 'property type_Townhouse': False, 'property type_Villa': False, 'closest_city_centre_Ballarat': False, 'closest_city_centre_Benalla': False, 'closest_city_centre_Bendigo': False, 'closest_city_centre_Cranbourne': False, 'closest_city_centre_Geelong': False, 'closest_city_centre_Horsham': False, 'closest_city_centre_Melbourne': False, 'closest_city_centre_Morwell': False, 'closest_city_centre_Sale': False, 'closest_city_centre_Shepparton': False, 'closest_city_centre_Swan Hill': False, 'closest_city_centre_Traralgon': False, 'closest_city_centre_Wangaratta': False, 'closest_city_centre_Warrnambool': False, 'closest_city_centre_Wodonga': False}

In [124]:
data[data.isnull().any(axis=1)]

Empty DataFrame
Columns: [beds, baths, parking, weekly rent amount, distance primary school, distance secondary school, is closest school good, distance university campus, distance to closest hospital, offence count 2023, estimated resident population (no.) 2011, total dwellings (no.) 2017, estimated resident population (no.) 2016, total dwellings (no.) 2019, estimated resident population (no.) 2021, total dwellings (no.) 2021, coastal, closest_cc_dist, dist_to_melb, predicted median equivalised total household income (weekly) ($) 2023, predicted median weekly household rental payment ($) 2023, predicted average family size (no. of persons) 2023, predicted employment ratio 2023, postcode_3000, postcode_3002, postcode_3003, postcode_3004, postcode_3006, postcode_3008, postcode_3011, postcode_3012, postcode_3013, postcode_3015, postcode_3016, postcode_3018, postcode_3019, postcode_3020, postcode_3021, postcode_3022, postcode_3023, postcode_3024, postcode_3025, postcode_3026, postcode_3027, postcode_3028, postcode_3029, postcode_3030, postcode_3031, postcode_3032, postcode_3033, postcode_3034, postcode_3036, postcode_3037, postcode_3038, postcode_3039, postcode_3040, postcode_3041, postcode_3042, postcode_3043, postcode_3044, postcode_3046, postcode_3047, postcode_3048, postcode_3049, postcode_3051, postcode_3052, postcode_3053, postcode_3054, postcode_3055, postcode_3056, postcode_3057, postcode_3058, postcode_3059, postcode_3060, postcode_3061, postcode_3064, postcode_3065, postcode_3066, postcode_3067, postcode_3068, postcode_3070, postcode_3071, postcode_3072, postcode_3073, postcode_3074, postcode_3075, postcode_3076, postcode_3078, postcode_3079, postcode_3081, postcode_3082, postcode_3083, postcode_3084, postcode_3085, postcode_3087, postcode_3088, postcode_3089, postcode_3091, postcode_3093, postcode_3094, ...]
Index: []

[0 rows x 467 columns]

In [125]:
# Create and fit the linear regression model
model = LinearRegression()
model.fit(X_train_scaled, y_train)

# Evaluate the model
train_score = model.score(X_train_scaled, y_train)
test_score = model.score(X_test_scaled, y_test)

print(f"Train R-squared: {train_score:.2f}")
print(f"Test R-squared: {test_score:.2f}")

Train R-squared: 0.52
Test R-squared: -12094714834491829752168448.00

In [138]:
import xgboost as xgb
from sklearn.metrics import r2_score
model = xgb.XGBRegressor(objective='reg:squarederror', n_estimators=100, learning_rate=0.1)
model.fit(X_train, y_train)
predictions = model.predict(X_test)
r2 = r2_score(y_test, predictions)

In [139]:
r2

0.7009489915877232

In [141]:
pd.DataFrame({"y_test": y_test, "predictions": predictions})

       y_test  predictions
1989      420   414.318390
6537      550   694.965759
9210      700   762.343994
1353      390   478.885590
8962      690   546.422363
...       ...          ...
7984      621   499.950775
2705      440   491.611145
10925    1200  1079.682861
7030      580   541.413452
9503      750   935.546143

[2247 rows x 2 columns]

In [140]:
from sklearn.metrics import mean_squared_error


# Calculate the mean squared error (MSE)
mse = mean_squared_error(y_test, predictions)

# Calculate the root mean squared error (RMSE)
rmse = np.sqrt(mse)

print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)

Mean Squared Error (MSE): 32798.31494630581
Root Mean Squared Error (RMSE): 181.10305062672413