In [1]:
import pandas as pd

In [30]:
# Accessing all the Victorian Postcodes
post_codes_file_path = "../data/landing/sa2/CG_POSTCODE_2021_SA2_2021.xlsx"
df = pd.read_excel(post_codes_file_path)

vic_df = df.loc[df["POSTCODE"].isin(range(3000,4000))]

vic_df = vic_df.dropna(subset=["SA2_CODE_2021"])

In [31]:

len(set(vic_df["SA2_CODE_2021"]))

525

In [32]:
vic_df["SA2_CODE_2021"].unique()

array([206041506, 206041124, 206041117, 206041503, 206041505, 206041504,
       206041119, 206041510, 206041127, 206051128, 206051512, 206041507,
       206041125, 206051514, 206051511, 206041508, 206041509, 206041118,
       213031348, 213031351, 213031350, 213021343, 213011338, 213031347,
       213031352, 213021344, 213021346, 213021341, 213021342, 213011570,
       213011332, 213011328, 213011336, 213011337, 213011333, 213011335,
       213011334, 213011569, 213041359, 213041360, 213041461, 213041462,
       213011329, 213041463, 213051582, 213051468, 213051589, 213051579,
       213051590, 213051363, 213051587, 213021345, 213051467, 213051584,
       213051586, 213051585, 213051361, 213051362, 213051588, 213051583,
       213051581, 213051580, 213051368, 213051466, 213051464, 206031113,
       206041120, 206031115, 206041121, 213031349, 210011534, 210011226,
       210011228, 210011533, 210051248, 213011340, 213011331, 213011339,
       213041575, 206031116, 206031501, 210011230, 206031502, 210011231,
       210011227, 210051245, 210031439, 210051250, 210031236, 206011498,
       210031537, 206011109, 210031538, 210031440, 210031536, 210031535,
       210051243, 210051242, 210051247, 206071140, 206011107, 206011496,
       206011495, 206011106, 209021526, 209021429, 206011497, 210051246,
       210031237, 210051544, 210051445, 210041240, 209041225, 210051441,
       210051542, 210051442, 210051543, 210051545, 210051443, 206071142,
       206071143, 206071141, 206071145, 206071139, 206021112, 206021110,
       206021500, 206021499, 209021525, 209021428, 209021524, 209021523,
       209041223, 209041530, 209041221, 209041529, 209041432, 209041433,
       209041431, 209011199, 209011201, 209011200, 209041220, 209011204,
       209041217, 209041216, 209021205, 209011196, 209011203, 209011198,
       209011197, 209011202, 209031213, 209031215, 209031210, 209031209,
       209031214, 209031212, 207011154, 207011521, 207011522, 207011148,
       207011147, 207021157, 207021156, 207031164, 207021159, 207021160,
       207021425, 211021261, 207021424, 211021262, 211031268, 211031265,
       211051275, 206071518, 206071517, 207011152, 207011519, 207011520,
       207011150, 207011149, 207011155, 207031165, 212051319, 207031167,
       207031163, 211041269, 207031162, 207031161, 211041271, 211041270,
       211041272, 211041273, 211031267, 211031266, 211031452, 211031451,
       211031450, 211051280, 211031263, 211051277, 211051281, 212011289,
       211051286, 211051283, 211051285, 211051278, 206061516, 206061515,
       206061138, 208041194, 206061136, 206061135, 208021177, 208041195,
       207011146, 212051326, 212051323, 212051324, 212051327, 212051322,
       212051321, 207031166, 211011254, 211011446, 211011251, 211011259,
       211011260, 211011449, 211051274, 211011257, 211051284, 212021453,
       211011255, 211011447, 211011448, 211051282, 208021178, 208021182,
       208021181, 208021176, 208021427, 208021426, 208021180, 212041309,
       212051325, 212051567, 212051568, 212041313, 212041310, 212041317,
       208031184, 212041460, 212041318, 212041566, 212041565, 212041316,
       212041459, 212031562, 212041564, 212041563, 212041312, 212021295,
       211011258, 211011256, 206051134, 206051513, 206051129, 208021179,
       208011172, 208011170, 208011169, 208021174, 208011171, 208011173,
       208031191, 208031188, 208011168, 208031190, 208031192, 208031189,
       208031183, 208031193, 208031187, 208031186, 208031185, 214011375,
       214011372, 214011373, 214011371, 214011370, 206051130, 203021043,
       203011035, 203011034, 203021047, 203021486, 203021488, 203021040,
       203021485, 203021037, 203021487, 203021042, 203011036, 203031053,
       203031489, 203021039, 203021045, 203021046, 203021044, 203031052,
       203031490, 203031048, 203031051, 203031049, 217031476, 217031473,
       217031475, 217031474, 217031472, 217031471, 217041477, 215011387,
       217011423, 217041478, 217041480, 217041479, 217011420, 217011421,
       217011422, 215011393, 215011392, 201031015, 201021012, 213041574,
       210041539, 210021232, 213041577, 213041576, 213041358, 213041573,
       213041572, 213041571, 213041578, 201021009, 213041353, 201011005,
       201011484, 201011481, 201011002, 201011483, 201011482, 201011001,
       201011006, 201031014, 201011007, 201021010, 201031013, 201011008,
       201021011, 202021028, 201031017, 215011386, 215011391, 215011394,
       215011389, 215011390, 215031400, 215011388, 210041540, 210041541,
       210021235, 210021234, 202021030, 204011060, 210021233, 202021031,
       202021026, 202021029, 202021027, 202031033, 201031016, 215021398,
       215021399, 215021395, 215021396, 215021470, 215021469, 215031405,
       216011410, 204011058, 215031401, 215031403, 202011024, 202011025,
       202011021, 202011020, 202011018, 202011019, 202031032, 202011023,
       202011022, 216011409, 216011407, 216011408, 216011406, 215031402,
       215031404, 216031419, 204011055, 216031415, 216031418, 216031594,
       216031416, 216031593, 216021413, 109031185, 216021411, 216021412,
       204011062, 209041224, 204011056, 204011059, 204011054, 204021064,
       204021063, 204021067, 204011057, 204021066, 204021065, 204031070,
       204031491, 204031073, 204031492, 204031072, 204031069, 109011172,
       204031075, 205021082, 113021260, 205021080, 205051099, 204011061,
       216021414, 204031071, 204031068, 209041437, 209041532, 209041435,
       209041436, 209041528, 209041531, 209041527, 209031211, 211051276,
       211051279, 212021297, 212021454, 212021299, 212021455, 212021293,
       212021554, 212031457, 212021456, 212031458, 212021553, 212011546,
       212011548, 212011550, 212011547, 212011551, 212011549, 212011552,
       205011076, 205011079, 205011077, 205011078, 205041095, 205051101,
       205041098, 205031090, 205041096, 205041094, 205051104, 205051102,
       205041493, 205041494, 205051103, 205051100, 205021086, 205031087,
       205021081, 205021083, 205021084, 205021085, 214011374, 214021385,
       212031308, 214021379, 214021378, 205031088, 205031091, 205031093,
       214021381, 214021592, 214021591, 214021382, 214021384, 214021377,
       214021383, 205031089, 205031092, 212031306, 212031561, 212031558,
       212031303, 212031560, 212031559, 214011376, 212031557, 212031300,
       212031304, 212031555, 212031556], dtype=object)

In [16]:
# Accessing all the Victorian Postcodes
post_codes_file_path = "../data/landing/sa2/CG_POSTCODE_2021_SA2_2021.xlsx"
df_codes = pd.read_excel(post_codes_file_path)

vic_df = df_codes.loc[df_codes["POSTCODE"].isin(range(3000,4000))]

# drop the null rows and get all of the SA2 codes
vic_df = vic_df.dropna(subset=["SA2_CODE_2021"])

sa2_codes = list((vic_df["SA2_CODE_2021"]))
sa2_codes = list(dict.fromkeys(sa2_codes))

cols = ["Estimated resident population (no.)", 
        'Median equivalised total household income (weekly) ($)',
        'Land area (ha)', 'Median weekly household rental payment ($)', 
        'Average family size (no. of persons)', 'Total families (no.)']

df = (pd.DataFrame(columns= cols, index=sa2_codes)).rename_axis('SA2_Code', axis=1)


folder_path = '../data/landing/suburb_info/'

trial_df = pd.read_csv(f"{folder_path}206041506.csv")

In [3]:
trial_df.head()

,Measure Code,Parent Description,Description,2011,2016,2017,2018,2019,2020,2021,2022
0,ERP_P_20,Estimated resident population - year ended 30 ...,Estimated resident population (no.),NaN,NaN,17005.0,17592.0,17955.0,18171.0,15998.0,16580.0
1,ERP_21,Estimated resident population - year ended 30 ...,Population density (persons/km2),NaN,NaN,7012.9,7255.0,7404.7,7493.8,6597.7,6837.7
2,ERP_M_20,Estimated resident population - year ended 30 ...,Estimated resident population - males (no.),NaN,NaN,8277.0,8561.0,8746.0,8864.0,7811.0,NaN
3,ERP_F_20,Estimated resident population - year ended 30 ...,Estimated resident population - females (no.),NaN,NaN,8728.0,9031.0,9209.0,9307.0,8187.0,NaN
4,ERP_19,Estimated resident population - year ended 30 ...,Median age - males (years),NaN,NaN,29.3,29.8,30.2,31.0,31.4,NaN

In [4]:
trial_df["Description"]

0                    Estimated resident population (no.)
1                       Population density (persons/km2)
2            Estimated resident population - males (no.)
3          Estimated resident population - females (no.)
4                             Median age - males (years)
                             ...
619                                  Negative income (%)
620      Income inadequately described or not stated (%)
621                                       Land area (ha)
622    Small-scale solar panel system installations (...
623               Solar water heater installations (no.)
Name: Description, Length: 624, dtype: object

In [37]:
pop_size = trial_df["2021"].loc[trial_df["Description"] == "Estimated resident population (no.)"].values[0]

income = trial_df["2021"].loc[trial_df["Description"] == 'Median equivalised total household income (weekly) ($)'].values[0]

area = trial_df["2021"].loc[trial_df["Description"] == 'Land area (ha)'].values[0]

median_rent = trial_df["2021"].loc[trial_df["Description"] == 'Median weekly household rental payment ($)'].values[0]

avg_family = trial_df["2021"].loc[trial_df["Description"] == 'Average family size (no. of persons)'].values[0]

total_family = trial_df["2021"].loc[trial_df["Description"] == 'Total families (no.)'].values[0]

In [38]:
df.head()

SA2_Code,Estimated resident population (no.),Median equivalised total household income (weekly) ($),Land area (ha),Median weekly household rental payment ($),Average family size (no. of persons),Total families (no.)
206041506,"0 15998.0 Name: 2021, dtype: float64","333 1281.0 Name: 2021, dtype: float64","621 242.5 Name: 2021, dtype: float64","498 381.0 Name: 2021, dtype: float64","486 2.6 Name: 2021, dtype: float64","485 3267.0 Name: 2021, dtype: float64"
206041124,NaN,NaN,NaN,NaN,NaN,NaN
206041117,NaN,NaN,NaN,NaN,NaN,NaN
206041503,NaN,NaN,NaN,NaN,NaN,NaN
206041505,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
print(pop_size)

15998.0

In [39]:
df.loc[206041506] = [pop_size, income, area, median_rent, avg_family, total_family]

In [40]:
df.head()

SA2_Code,Estimated resident population (no.),Median equivalised total household income (weekly) ($),Land area (ha),Median weekly household rental payment ($),Average family size (no. of persons),Total families (no.)
206041506,15998.0,1281.0,242.5,381.0,2.6,3267.0
206041124,NaN,NaN,NaN,NaN,NaN,NaN
206041117,NaN,NaN,NaN,NaN,NaN,NaN
206041503,NaN,NaN,NaN,NaN,NaN,NaN
206041505,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
trial_df = pd.read_csv(f"{folder_path}206041127.csv")

try:
    pop_size = trial_df["2021"].loc[trial_df["Description"] == "Estimated resident population (no.)"].values[0]

    income = trial_df["2021"].loc[trial_df["Description"] == 'Median equivalised total household income (weekly) ($)']

    area = trial_df["2021"].loc[trial_df["Description"] == 'Land area (ha)'].values[0]

    median_rent = trial_df["2021"].loc[trial_df["Description"] == 'Median weekly household rental payment ($)'].values[0]

    avg_family = trial_df["2021"].loc[trial_df["Description"] == 'Average family size (no. of persons)'].values[0]

    total_family = trial_df["2021"].loc[trial_df["Description"] == 'Total families (no.)'].values[0]

except IndexError:
    print("Something went wrong")
# print(pop_size)

print(trial_df["2021"].loc[trial_df["Description"] == "Estimated resident population (no.)"].isna().values[0])

Something went wrong
True

In [50]:
import numpy as np

print(np.nan)

print(pop_size == np.nan)

nan
False